Repository Scille/parsec-cloud, pull requests merged in 2022-05, with the labels that each got.

#2227 Small improvement in gui's NavigationBarWidget typing
  newsfragments/2227.empty.rst
  parsec/core/gui/navigation_bar_widget.py
Labels: enhancement

#2211 Handle saving from Apple softwares on FUSE drives
  newsfragments/2211.bugfix.rst
  parsec/core/mountpoint/fuse_operations.py
  parsec/core/mountpoint/fuse_runner.py
  parsec/core/mountpoint/thread_fs_access.py
Labels: mountpoint, macos

#2336 Fix multierror handling in remote_loader
  parsec/core/fs/remote_loader.py
  parsec/service_nursery.py
  parsec/utils.py
Labels: bug

#2342 use pip as module to update itself
  .azure-pipelines.yml
Labels: bug, ci

#2320 Add RELEASE.md to document release process
  .readthedocs.yml
  docs/architecture.rst
  docs/conf.py
  docs/cryptography.rst
  docs/development/functional_architecture.rst
  docs/development/index.rst
  docs/development/quickstart.rst
  docs/development/release.rst
  docs/history.rst
  docs/hosting_server.rst
  docs/index.rst
  docs/introduction.rst
  docs/roles.rst
  docs/userguide/index.rst
  docs/userguide/installation.rst
  docs/userguide/new_device.rst
  docs/userguide/new_organization.rst
  docs/userguide/new_user.rst
  docs/userguide/revoke_user.rst
  docs/userguide/share_data.rst
  misc/license_headers.py
Labels: docs
