Repository Scille/parsec-cloud, pull requests merged in 2022-10, with the labels that each got.

#3200 update required python version in documentation
  README.rst
  docs/hosting_server.rst
  docs/locale/fr/LC_MESSAGES/development.po
  docs/locale/fr/LC_MESSAGES/hosting_server.po
  docs/locale/fr/LC_MESSAGES/userguide.po
  docs/userguide/installation.rst
  packaging/macOS/README.md
Labels: docs

#3207 Allow to run `cargo test` for the root crate
  .github/workflows/ci.yml
  Cargo.toml
  pyproject.toml
Labels: rust

#3203 Remove unused rust dependencies using `cargo-udeps`.
  Cargo.lock
  oxidation/libparsec/crates/client_types/Cargo.toml
  oxidation/libparsec/crates/core/Cargo.toml
  oxidation/libparsec/crates/crypto/Cargo.toml
  oxidation/libparsec/crates/platform_native/Cargo.toml
  oxidation/libparsec/crates/protocol/Cargo.toml
  oxidation/libparsec/crates/tests_fixtures/Cargo.toml
  oxidation/libparsec/crates/types/Cargo.toml
Labels: dependencies, rust

#3032 Oxidation replace protocol user
  misc/gen_types.py
  newsfragments/3018.empty.rst
  oxidation/generate_test_data/protocol/user.py
  oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/human_find.json
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/user_get.json
  oxidation/libparsec/crates/protocol/src/lib.rs
  oxidation/libparsec/crates/protocol/tests/test_user.rs
  oxidation/libparsec/crates/serialization_format/src/parser/utils.rs
  oxidation/libparsec_python/libparsec/types.py
  oxidation/libparsec_python/src/lib.rs
  oxidation/libparsec_python/src/protocol/mod.rs
  oxidation/libparsec_python/src/protocol/user.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/certif.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/_parsec_pyi/trustchain.pyi
  parsec/api/protocol/user.py
  parsec/backend/user.py
  parsec/core/backend_connection/cmds.py
  parsec/core/invite/claimer.py
  parsec/core/invite/greeter.py
  parsec/core/logged_core.py
  parsec/core/recovery.py
  parsec/core/remote_devices_manager.py
  parsec/test_utils/organization.py
  src/lib.rs
  src/protocol/cmds.rs
  src/protocol/mod.rs
  src/protocol/user.rs
  src/trustchain.rs
  tests/backend/common.py
  tests/backend/test_pki.py
  tests/backend/user/test_device_create.py
  tests/backend/user/test_human_find.py
  tests/backend/user/test_user_create.py
  tests/backend/user/test_user_get.py
  tests/backend/user/test_user_revoke.py
  tests/core/fs/userfs/test_sharing.py
  tests/core/test_trustchain.py
  tests/core/test_trustchain_stateful.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#3210 Chore
  oxidation/libparsec/crates/types/src/certif.rs
  src/addrs.rs
  src/binding_utils.rs
  src/invite.rs
Labels: rust

#3211 Enhance Regex
  oxidation/libparsec/crates/types/src/regex.rs
  src/regex.rs
Labels: rust

#3214 Add test to check regex compat
  oxidation/libparsec/crates/client_types/src/local_manifest.rs
  oxidation/libparsec/crates/types/src/regex.rs
  src/binding_utils.rs
  src/regex.rs
Labels: bug, rust

#3223 Fully oxidize `InvitationEmailSentStatus`
  newsfragments/3220.empty.rst
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/invite.py
  parsec/backend/invite.py
  parsec/core/gui/greet_device_widget.py
  parsec/core/gui/users_widget.py
  parsec/core/logged_core.py
  src/protocol/invite.rs
  tests/backend/invite/test_manage_invitations.py
  tests/core/gui/devices_widget/test_greet.py
Labels: refactor, python, rust

#3239 Add mypy to pyi files
  mypy.ini
  parsec/_parsec_pyi/addrs.pyi
  parsec/_parsec_pyi/certif.pyi
  parsec/_parsec_pyi/crypto.pyi
  parsec/_parsec_pyi/ids.pyi
  parsec/_parsec_pyi/invite.pyi
  parsec/_parsec_pyi/local_device.pyi
  parsec/_parsec_pyi/local_manifest.pyi
  parsec/_parsec_pyi/manifest.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/_parsec_pyi/time.pyi
  parsec/_parsec_pyi/trustchain.pyi
  parsec/backend/user.py
  parsec/core/fs/storage/manifest_storage.py
  parsec/core/fs/workspacefs/sync_transactions.py
Labels: python

#3209 Oxidize trustchain error
  newsfragments/3171.empty.rst
  parsec/_parsec.pyi
  parsec/_parsec_pyi/trustchain.pyi
  parsec/core/remote_devices_manager.py
  parsec/core/trustchain.py
  src/binding_utils.rs
  src/lib.rs
  src/trustchain.rs
  tests/core/test_trustchain.py
Labels: python, rust

#3251 Oxidation fix badtimestamp compat
  newsfragments/3249.empty.rst
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_create.json
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_start_reencryption_maintenance.json
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_update_roles.json
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_create.json
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_update.json
  oxidation/libparsec/crates/protocol/tests/test_realm.rs
  oxidation/libparsec/crates/protocol/tests/test_vlob.rs
  src/protocol/mod.rs
  src/protocol/realm.rs
  src/protocol/vlob.rs
Labels: bug, python, rust

#3277 Add timeout for `use-pre-commit` action
  .github/workflows/ci.yml
  newsfragments/3276.empty.rst
  tests/test_time_provider.py
Labels: bug, ci

#3259 Improve `check_newsfragment` check.
  .github/scripts/check_newsfragments.py
Labels: enhancement, ci

#3260 Cargo build ignore changes in json schema
  Cargo.lock
  newsfragments/3174.empty.rst
  oxidation/libparsec/crates/client_types/Cargo.toml
  oxidation/libparsec/crates/client_types/build.rs
  oxidation/libparsec/crates/protocol/Cargo.toml
  oxidation/libparsec/crates/protocol/build.rs
  oxidation/libparsec/crates/types/Cargo.toml
  oxidation/libparsec/crates/types/build.rs
Labels: enhancement, rust

#3263 Updated macFUSE installation doc
  docs/locale/fr/LC_MESSAGES/userguide.po
  docs/userguide/installation.rst
  newsfragments/3262.empty.rst
  parsec/core/gui/tr/parsec_en.po
  parsec/core/gui/tr/parsec_fr.po
Labels: docs

#3306 Fix typo in macfuse doc
  docs/locale/fr/LC_MESSAGES/userguide.po
Labels: docs

#3311 Create a custom profile for rust test
  .github/workflows/ci.yml
  Cargo.toml
  newsfragments/3307.empty.rst
Labels: rust

#3314 Remove `ubuntu-18.04` usage in the CI
  .github/workflows/package-ci.yml
  newsfragments/2975.empty.rst
Labels: ci, dependencies, github_actions

#3316 Bump `actions/checkout` to `v3.1.0`
  .github/workflows/ci.yml
  .github/workflows/package-ci.yml
  newsfragments/3315.empty.rst
Labels: ci, dependencies, github_actions

#3282 Remplace `actions-rs/toolchain` by `dtolnay/rust-toolchain`
  .github/actions/setup-rust/action.yml
  newsfragments/3261.empty.rst
  newsfragments/3281.empty.rst
Labels: enhancement, ci, dependencies

#3324 Oxidation fix unknown status deserialization
  newsfragments/3323.empty.rst
  oxidation/libparsec/crates/protocol/tests/test_common.rs
  oxidation/libparsec/crates/serialization_format/src/parser/protocol.rs
Labels: bug, rust

#3330 Dump `poetry` install logs on failure
  .github/actions/setup-python-poetry/action.yml
Labels: enhancement, ci

#3121 Relax `test_eyeballs` expected delay timeout to 1s
  oxidation/libparsec/crates/platform_async/tests/eyeballs.rs
Labels: bug, rust

#3321 Add mypy for backend postgresql
  mypy.ini
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/__init__.py
  parsec/api/protocol/base.py
  parsec/backend/block.py
  parsec/backend/events.py
  parsec/backend/invite.py
  parsec/backend/message.py
  parsec/backend/organization.py
  parsec/backend/ping.py
  parsec/backend/postgresql/block.py
  parsec/backend/postgresql/factory.py
  parsec/backend/postgresql/handler.py
  parsec/backend/postgresql/invite.py
  parsec/backend/postgresql/message.py
  parsec/backend/postgresql/organization.py
  parsec/backend/postgresql/pki.py
  parsec/backend/postgresql/realm.py
  parsec/backend/postgresql/realm_queries/create.py
  parsec/backend/postgresql/realm_queries/get.py
  parsec/backend/postgresql/realm_queries/maintenance.py
  parsec/backend/postgresql/realm_queries/update_roles.py
  parsec/backend/postgresql/sequester.py
  parsec/backend/postgresql/sequester_export.py
  parsec/backend/postgresql/user.py
  parsec/backend/postgresql/user_queries/create.py
  parsec/backend/postgresql/user_queries/find.py
  parsec/backend/postgresql/user_queries/get.py
  parsec/backend/postgresql/user_queries/revoke.py
  parsec/backend/postgresql/utils.py
  parsec/backend/postgresql/vlob.py
  parsec/backend/postgresql/vlob_queries/maintenance.py
  parsec/backend/postgresql/vlob_queries/read.py
  parsec/backend/postgresql/vlob_queries/utils.py
  parsec/backend/postgresql/vlob_queries/write.py
  parsec/backend/realm.py
  parsec/backend/user.py
  parsec/backend/utils.py
  parsec/backend/vlob.py
  parsec/stubs/triopg/__init__.pyi
  parsec/stubs/triopg/_triopg.pyi
  parsec/stubs/triopg/py.typed
Labels: enhancement, python

#3295 Add mypy for backend asgi
  mypy.ini
  parsec/backend/asgi/__init__.py
  parsec/backend/asgi/administration.py
  parsec/backend/asgi/redirect.py
  parsec/backend/asgi/rpc.py
  parsec/backend/asgi/ws.py
Labels: enhancement, python

#3285 Add mypy to backend memory
  mypy.ini
  parsec/backend/app.py
  parsec/backend/invite.py
  parsec/backend/memory/block.py
  parsec/backend/memory/factory.py
  parsec/backend/memory/invite.py
  parsec/backend/memory/message.py
  parsec/backend/memory/organization.py
  parsec/backend/memory/ping.py
  parsec/backend/memory/pki.py
  parsec/backend/memory/realm.py
  parsec/backend/memory/sequester.py
  parsec/backend/memory/user.py
  parsec/backend/memory/vlob.py
  parsec/backend/organization.py
  parsec/backend/user_type.py
Labels: enhancement, python

#3348 Add mypy typing to `parsec.core.pki.*`
  mypy.ini
  newsfragments/3339.empty.rst
  parsec/core/pki/accepter.py
  parsec/core/pki/plumbing.py
  parsec/core/pki/submitter.py
Labels: enhancement, python

#3304 Add mypy support `parsec.core.mountpoint.*`
  mypy.ini
  newsfragments/3303.empty.rst
  parsec/core/mountpoint/fuse_operations.py
  parsec/core/mountpoint/fuse_runner.py
  parsec/core/mountpoint/manager.py
  parsec/core/mountpoint/thread_fs_access.py
  parsec/core/mountpoint/winfsp_operations.py
  parsec/core/mountpoint/winfsp_runner.py
  parsec/core/mountpoint/winify.py
Labels: enhancement, python

#3356 Enable mypy backend
  mypy.ini
  newsfragments/3355.empty.rst
  parsec/_parsec_pyi/protocol.pyi
  parsec/backend/app.py
  parsec/backend/asgi/rpc.py
  parsec/backend/asgi/ws.py
  parsec/backend/backend_events.py
  parsec/backend/block.py
  parsec/backend/blockstore.py
  parsec/backend/client_context.py
  parsec/backend/config.py
  parsec/backend/events.py
  parsec/backend/handshake.py
  parsec/backend/invite.py
  parsec/backend/memory/invite.py
  parsec/backend/message.py
  parsec/backend/organization.py
  parsec/backend/ping.py
  parsec/backend/pki.py
  parsec/backend/postgresql/invite.py
  parsec/backend/raid1_blockstore.py
  parsec/backend/raid5_blockstore.py
  parsec/backend/realm.py
  parsec/backend/s3_blockstore.py
  parsec/backend/sequester.py
  parsec/backend/swift_blockstore.py
  parsec/backend/templates/__init__.py
  parsec/backend/user.py
  parsec/backend/utils.py
  parsec/backend/vlob.py
  parsec/backend/webhooks.py
Labels: enhancement, python

#3334 Enable mypy api protocol
  mypy.ini
  newsfragments/3333.empty.rst
  parsec/api/protocol/base.py
  parsec/api/protocol/handshake.py
Labels: enhancement, python

#3332 Enable mypy api data
  mypy.ini
  newsfragments/3331.empty.rst
  parsec/api/data/certif.py
  parsec/api/data/message.py
  parsec/api/data/pki.py
Labels: enhancement, python

#3358 Remove unused class
  parsec/api/data/manifest.py
  parsec/api/protocol/__init__.py
  parsec/api/protocol/types.py
  parsec/types.py
Labels: enhancement, python

#3325 Add mypy to `core.backend_connection`
  mypy.ini
  newsfragments/3319.empty.rst
  parsec/_parsec_pyi/addrs.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/core/backend_connection/anonymous.py
  parsec/core/backend_connection/apiv1_annonymous.py
  parsec/core/backend_connection/authenticated.py
  parsec/core/backend_connection/cmds.py
  parsec/core/backend_connection/expose_cmds.py
  parsec/core/backend_connection/invited.py
  parsec/core/backend_connection/proxy.py
  parsec/core/backend_connection/transport.py
  parsec/core/fs/remote_loader.py
  parsec/core/fs/userfs/userfs.py
  parsec/core/fs/workspacefs/workspacefs.py
  parsec/core/pki/submitter.py
  parsec/core/remote_devices_manager.py
  parsec/core/types/__init__.py
  parsec/core/types/organizations.py
  parsec/stubs/pypac/__init__.pyi
  parsec/stubs/pypac/py.typed
  tests/core/backend_connection/test_authenticated_conn.py
Labels: enhancement, python

#3360 Enable mypy on api
  mypy.ini
  newsfragments/3264.empty.rst
Labels: enhancement, python

#3132 Per organization stats cli
  newsfragments/3109.misc.rst
  parsec/api/rest.py
  parsec/backend/asgi/administration.py
  parsec/backend/memory/block.py
  parsec/backend/memory/organization.py
  parsec/backend/memory/realm.py
  parsec/backend/organization.py
  parsec/backend/postgresql/organization.py
  parsec/cli_utils.py
  parsec/core/cli/__init__.py
  parsec/core/cli/stats_organization.py
  tests/backend/test_administration_rest_api.py
  tests/backend/test_server_stats.py
  tests/common/binder.py
  tests/test_cli.py
Labels: enhancement, python

#3374 Rename module `apiv1_anonymous` to correct typo in it's name
  parsec/core/backend_connection/__init__.py
  parsec/core/backend_connection/apiv1_anonymous.py
  parsec/core/backend_connection/expose_cmds.py
Labels: python

#3403 Config `winfsp` version that was missing
  .github/workflows/ci.yml
  newsfragments/3404.empty.rst
Labels: bug, ci

#3388 Add mypy typing for `core.gui.color`
  mypy.ini
  newsfragments/3373.empty.rst
  parsec/core/gui/color.py
Labels: enhancement, python

#3370 Update InvitationType
  parsec/api/protocol/handshake.py
  tests/backend/invite/test_exchange.py
  tests/backend/invite/test_manage_invitations.py
Labels: python

#3368 Use asyncio.run
  tests/common/postgresql.py
Labels: enhancement, python

#3255 Add mypy for `protocol.invite`
  mypy.ini
  parsec/core/backend_connection/apiv1_anonymous.py
  parsec/core/backend_connection/cmds.py
  parsec/core/backend_connection/expose_cmds.py
  parsec/core/backend_connection/invited.py
  parsec/core/invite/organization.py
  parsec/core/pki/accepter.py
Labels: enhancement, python

#3399 Disable news fragments check
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/actions/paths-filter/action.yml
  .github/actions/paths-filter/filters.yml
  .github/workflows/ci.yml
Labels: enhancement, ci

#3283 mypy: Added missing types for `parsec.core.types`
  mypy.ini
  newsfragments/3284.empty.rst
  parsec/_parsec_pyi/local_manifest.pyi
  parsec/core/types/backend_address.py
  parsec/core/types/pki.py
  parsec/serde/fields.py
  parsec/stubs/marshmallow/fields.pyi
Labels: enhancement, python

#3369 Update packb since we handle datetime in pg
  parsec/serde/packing.py
Labels: python

#2646 Recover device
  .github/workflows/ci.yml
  Cargo.lock
  newsfragments/2645.empty.rst
  oxidation/bindings/common/src/lib.rs
  oxidation/libparsec/crates/client_types/src/error.rs
  oxidation/libparsec/crates/client_types/src/local_device.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/src/local_manifest.rs
  oxidation/libparsec/crates/client_types/tests/test_local_manifest.rs
  oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/user_storage.rs
  oxidation/libparsec/crates/crypto/Cargo.toml
  oxidation/libparsec/crates/crypto/src/common/mod.rs
  oxidation/libparsec/crates/crypto/src/common/secret.rs
  oxidation/libparsec/crates/crypto/src/lib.rs
  oxidation/libparsec/crates/crypto/src/macros.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/secret.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/secret.rs
  oxidation/libparsec/crates/crypto/tests/common/mod.rs
  oxidation/libparsec/crates/crypto/tests/private.rs
  oxidation/libparsec/crates/crypto/tests/secret.rs
  oxidation/libparsec/crates/tests_fixtures/src/lib.rs
  oxidation/libparsec/crates/types/src/invite.rs
  oxidation/libparsec/crates/types/src/lib.rs
  oxidation/libparsec/crates/types/src/manifest.rs
  src/api_crypto.rs
  src/regex.rs
Labels: rust

#3397 Use rust generate_shared_secret_key
  parsec/_parsec_pyi/crypto.pyi
  parsec/core/invite/claimer.py
  parsec/core/invite/greeter.py
  parsec/crypto.py
  src/api_crypto.rs
Labels: python, rust

#3405 Add mypy core gui licence loading login widget
  mypy.ini
  newsfragments/3375.empty.rst
  parsec/core/gui/license_widget.py
  parsec/core/gui/loading_widget.py
  parsec/core/gui/login_widget.py
  parsec/core/gui/trio_jobs.py
Labels: enhancement, python

#3320 Improve `MyPy` typing for `core.cli`
  mypy.ini
  newsfragments/3318.empty.rst
  parsec/_parsec_pyi/protocol.pyi
  parsec/cli_utils.py
  parsec/core/cli/__init__.py
  parsec/core/cli/bootstrap_organization.py
  parsec/core/cli/create_organization.py
  parsec/core/cli/create_workspace.py
  parsec/core/cli/human_find.py
  parsec/core/cli/invitation.py
  parsec/core/cli/list_devices.py
  parsec/core/cli/pki.py
  parsec/core/cli/recovery.py
  parsec/core/cli/reencrypt_workspace.py
  parsec/core/cli/rsync.py
  parsec/core/cli/run.py
  parsec/core/cli/share_workspace.py
  parsec/core/cli/stats_organization.py
  parsec/core/cli/status_organization.py
  parsec/core/cli/utils.py
  parsec/core/config.py
  parsec/core/gui/enrollment_widget.py
  parsec/core/logged_core.py
  parsec/core/pki/__init__.py
  parsec/core/pki/accepter.py
  parsec/core/pki/submitter.py
  tests/core/test_rsync.py
  tests/test_cli.py
Labels: enhancement, python
