Repository Scille/parsec-cloud, pull requests merged in 2022-07, with the labels that each got.

#2523 migrate QA job to github action
  .github/scripts/check_commit_signature.py
  .github/scripts/check_news_fragment.py
  .github/workflows/quality-assurance.yml
  newsfragments/2524.empty.rst
Labels: ci

#2570 Feat/2565 reduce dependabot charge volume
  .github/dependabot.yml
  newsfragments/2565.empty.rst
Labels: ci

#2575 add trigger on main branch + debug & correct rust-cache
  .github/workflows/quality-assurance.yml
Labels: ci

#2613 Fix/2611 pre commit GitHub action dont correctly work with the cache
  .github/actions/use-pre-commit/action.yml
  .github/workflows/quality-assurance.yml
  newsfragments/2611.empty.rst
  newsfragments/2617.empty.rst
Labels: bug, enhancement, ci

#2593 Yolo/fix/ga qa skip news fragment on main branch
  .github/workflows/quality-assurance.yml
Labels: ci

#2623 add badge for quality assurance
  README.rst
Labels: docs

#2635 Feat/create ga setup rust
  .github/actions/setup-rust/action.yml
  .github/actions/use-pre-commit/action.yml
  .github/workflows/quality-assurance.yml
  newsfragments/2636.empty.rst
Labels: ci, rust

#2638 rename generated artifact by libparsec python
  newsfragments/2637.empty.rst
  oxidation/libparsec_python/Cargo.toml
  oxidation/libparsec_python/pyproject.toml
Labels: bug, rust

#2639 add CI workflow to run rust build & test on linux
  .github/actions/setup-rust/action.yml
  .github/workflows/linux-ci.yml
  .github/workflows/quality-assurance.yml
  newsfragments/2634.empty.rst
Labels: ci, linux, rust

#2641 add CI workflow to test python codebase on linux
  .github/workflows/linux-ci.yml
  newsfragments/2640.empty.rst
Labels: ci, linux, python

#2460 Feat/2419 impl parseccorebackend connectionauthenticatedpy in rust
  Cargo.lock
  newsfragments/2419.empty.rst
  oxidation/libparsec/crates/client_connection/Cargo.toml
  oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs
  oxidation/libparsec/crates/client_connection/src/command_error.rs
  oxidation/libparsec/crates/client_connection/src/lib.rs
  oxidation/libparsec/crates/client_connection/tests/auth_cmds.rs
  oxidation/libparsec/crates/client_connection/tests/utils/mod.rs
  oxidation/libparsec/crates/client_connection/tests/utils/server.rs
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/device_create.json
  oxidation/libparsec/crates/protocol/src/error.rs
  oxidation/libparsec/crates/protocol/src/handshake.rs
  oxidation/libparsec/crates/types/src/addr.rs
Labels: rust

#2608 Feat/2589 configure a GitHub action that is manually trigered to add issue that arent assign to a project to the orga project
  .editorconfig
  .github/scripts/notary/graphql/add_item_to_project_v2.graphql
  .github/scripts/notary/graphql/get_project_v2_id.graphql
  .github/scripts/notary/graphql/list_field_id.graphql
  .github/scripts/notary/graphql/update_field.graphql
  .github/scripts/notary/lib.sh
  .github/workflows/project-notary.yml
  newsfragments/2589.empty.rst
Labels: ci

#2655 Migrate Windows ci to Github action for python-only
  .github/workflows/windows-ci.yml
  newsfragments/2654.empty.rst
Labels: windows, ci, python

#2660 Feat/2659 decommission of qa step in azure pipeline
  .azure-pipelines.yml
  newsfragments/2659.empty.rst
Labels: ci

#2671 Fix subprocess run on Windows for test_cli that could lead not to use the correct virtualenv
  .github/workflows/windows-ci.yml
  tests/core/gui/conftest.py
  tests/test_cli.py
Labels: bug, ci, python

#2668 Convert notary workflow to simple script
  .github/scripts/notary/README.md
  .github/scripts/notary/script.sh
  .github/workflows/project-notary.yml
Labels: ci

#2665 Feat/2661 migrate packaging linux step to GitHub action
  .github/workflows/package-linux.yml
  newsfragments/2661.empty.rst
Labels: ci, linux, snap

#2657 Migration MacOS CI to Github Action python-only part
  .github/workflows/macos-ci.yml
  newsfragments/2656.empty.rst
Labels: ci, macos, python

#2681 Fix web client
  newsfragments/2680.empty.rst
  oxidation/bindings/common/src/lib.rs
Labels: bug, gui, rust

#2684 Fix HumanHandle
  oxidation/libparsec/crates/types/src/id.rs
  tests/api/test_types.py
Labels: bug, rust

#2682 Oxidation fix remove dir all windows
  Cargo.lock
  newsfragments/2653.empty.rst
  oxidation/libparsec/crates/tests_fixtures/Cargo.toml
  oxidation/libparsec/crates/tests_fixtures/src/lib.rs
Labels: bug, windows, rust

#2685 Rename jobs name
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/package-linux.yml
  .github/workflows/windows-ci.yml
Labels: enhancement, ci

#2683 improve debugging
  .github/workflows/linux-ci.yml
Labels: ci, linux

#2690 Correct `needs` for job `package-linux-build-snap`
  .github/workflows/package-linux.yml
Labels: bug, ci

#2691 Correct `Set snap build version`
  .github/workflows/package-linux.yml
Labels: bug, ci, linux

#2698 Yolo/correct trigger tags and comment
  .github/workflows/package-linux.yml
Labels: bug, ci, docs

#2700 Yolo/rewrite dev docs
  docs/development/quickstart.rst
  docs/development/release.rst
Labels: enhancement, docs

#2675 add windows packaging workflow
  .github/workflows/package-windows.yml
  newsfragments/2662.empty.rst
Labels: windows, ci

#2676 Feat/2663 migrate packaging macos steps to GitHub action
  .github/workflows/package-macos.yml
  newsfragments/2663.empty.rst
  packaging/macOS/freeze_program.py
  packaging/macOS/pyinstaller.spec
Labels: ci, macos

#2713 Feat/2704 normalize freeze program and pyinstallerspec between macos and windows
  newsfragments/2704.empty.rst
  packaging/win32/freeze_program.py
  packaging/win32/pyinstaller.spec
Labels: windows, ci

#2720 Link sqlite
  Cargo.lock
  oxidation/libparsec/crates/core_fs/Cargo.toml
Labels: rust

#2651 Feat/2650 migrate windows ci test build rust code
  .github/workflows/windows-ci.yml
  newsfragments/2650.empty.rst
Labels: windows, ci, rust
