Repository Scille/parsec-cloud, pull requests merged in 2022-12, with the labels that each got.

#3655 Fix `test_transport` requiring `VERSION` env var
  oxidation/libparsec/crates/platform_native/tests/test_transport.rs
Labels: bug, inconsistent testing, rust

#3662 Update dependabot config
  .github/dependabot.yml
Labels: enhancement, ci

#3656 Oxidize protocol error
  oxidation/libparsec/crates/protocol/src/error.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol/__init__.pyi
  parsec/_parsec_pyi/protocol/error.pyi
  parsec/api/protocol/__init__.py
  parsec/api/protocol/base.py
  parsec/api/protocol/handshake.py
  parsec/backend/asgi/ws.py
  parsec/backend/handshake.py
  parsec/backend/utils.py
  parsec/core/backend_connection/anonymous.py
  parsec/core/backend_connection/cmds.py
  parsec/core/backend_connection/transport.py
  parsec/core/pki/submitter.py
  src/protocol/block.rs
  src/protocol/cmds.rs
  src/protocol/error.rs
  src/protocol/events.rs
  src/protocol/invite.rs
  src/protocol/message.rs
  src/protocol/mod.rs
  src/protocol/organization.rs
  src/protocol/ping.rs
  src/protocol/pki.rs
  src/protocol/realm.rs
  src/protocol/user.rs
  src/protocol/vlob.rs
Labels: python, rust

#3747 Use new notation for poetry dev deps.
  pyproject.toml
Labels: dependencies, python

#3748 Chore protocol test
  oxidation/libparsec/crates/protocol/tests/test_block.rs
  oxidation/libparsec/crates/protocol/tests/test_common.rs
  oxidation/libparsec/crates/protocol/tests/test_events.rs
  oxidation/libparsec/crates/protocol/tests/test_invite.rs
  oxidation/libparsec/crates/protocol/tests/test_organization.rs
  oxidation/libparsec/crates/protocol/tests/test_realm.rs
  oxidation/libparsec/crates/protocol/tests/test_user.rs
  oxidation/libparsec/crates/protocol/tests/test_vlob.rs
Labels: rust

#3750 Fix human handle
  newsfragments/3749.bugfix.rst
  oxidation/libparsec/crates/types/src/id.rs
Labels: rust

#3633 Oxidize pki enrollment status enum
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol/pki.pyi
  parsec/api/protocol/__init__.py
  parsec/api/protocol/pki.py
  parsec/backend/postgresql/pki.py
  parsec/core/pki/submitter.py
  src/protocol/mod.rs
  src/protocol/pki.rs
  tests/backend/test_pki.py
Labels: python, rust

#3743 Oxidize api version
  oxidation/libparsec/crates/protocol/src/handshake.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/misc.pyi
  parsec/api/protocol/handshake.py
  parsec/api/protocol/types.py
  parsec/api/version.py
  parsec/serde/fields.py
  parsec/serde/packing.py
  src/lib.rs
  src/misc.rs
  src/protocol/mod.rs
  tests/backend/test_compatibility.py
Labels: refactor, python, rust

#3619 Add client version in logs
  parsec/_parsec_pyi/addrs.pyi
  parsec/backend/asgi/rpc.py
  parsec/backend/asgi/ws.py
  tests/backend/test_rpc_handshake.py
  tests/backend/test_ws_handshake.py
Labels: enhancement, python

#3737 Oxidize load of ignore files pattern
  oxidation/libparsec/crates/types/src/error.rs
  oxidation/libparsec/crates/types/src/regex.rs
  parsec/_parsec_pyi/regex.pyi
  parsec/core/logged_core.py
  src/regex.rs
Labels: refactor, python, rust

#3770 UnboundLocalError: local variable `icon_scaled` referenced before assignment
  newsfragments/3769.bugfix.rst
  parsec/core/gui/custom_widgets.py
Labels: bug, gui, python

#3771 Bump npm packages to remove some deprecated one
  oxidation/client/electron/package-lock.json
  oxidation/client/electron/package.json
Labels: dependencies, Ionic

#3775 Updated the function that choses the drive icon
  parsec/core/mountpoint/winfsp_runner.py
  parsec/core/win_registry.py
Labels: windows

#3787 Remove dead code in `parsec` and `tests`
  parsec/api/protocol/__init__.py
  parsec/api/protocol/types.py
  parsec/core/config.py
  parsec/core/local_device.py
  parsec/core/mountpoint/winfsp_operations.py
  parsec/test_utils/organization.py
  parsec/win32.py
  tests/backend/common.py
  tests/backend/test_postgres_db.py
Labels: refactor, python

#3206 Implement list_available_devices with generator
  newsfragments/3167.empty.rst
  oxidation/bindings/common/src/lib.rs
  oxidation/bindings/electron/src/index.d.ts
  oxidation/bindings/electron/src/meths.rs
  oxidation/bindings/generator/api.py
  oxidation/bindings/generator/templates/binding_electron_index.d.ts.j2
  oxidation/bindings/generator/templates/binding_electron_meths.rs.j2
  oxidation/bindings/generator/templates/binding_web_meths.rs.j2
  oxidation/bindings/generator/templates/client_plugin_definitions.d.ts.j2
  oxidation/bindings/web/src/meths.rs
  oxidation/client/src/plugins/libparsec/definitions.d.ts
  oxidation/client/src/plugins/libparsec/index.ts
  oxidation/libparsec/Cargo.toml
  oxidation/libparsec/crates/client_types/src/lib.rs
  oxidation/libparsec/crates/client_types/src/local_device.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/src/local_manifest.rs
  oxidation/libparsec/crates/client_types/src/path.rs
  oxidation/libparsec/crates/client_types/tests/test_local_device_file.rs
  oxidation/libparsec/crates/core/src/trustchain.rs
  oxidation/libparsec/crates/tests_fixtures/src/lib.rs
  oxidation/libparsec/crates/types/src/certif.rs
  oxidation/libparsec/crates/types/src/error.rs
  oxidation/libparsec/crates/types/src/id.rs
  oxidation/libparsec/crates/types/src/manifest.rs
  oxidation/libparsec/crates/types/src/pki.rs
  oxidation/libparsec/crates/types/src/time.rs
  oxidation/libparsec/crates/types/tests/test_manifest.rs
  oxidation/libparsec/src/lib.rs
  src/binding_utils.rs
  src/data/certif.rs
  src/ids.rs
  src/local_device.rs
Labels: python, rust

#3790 Replace classmethod to classattr for value that should be constant in the rust python binding
  parsec/_parsec_pyi/enumerate.pyi
  parsec/_parsec_pyi/protocol/realm.pyi
  parsec/backend/memory/organization.py
  parsec/backend/memory/realm.py
  parsec/backend/postgresql/organization.py
  parsec/backend/realm.py
  parsec/core/cli/invitation.py
  parsec/core/cli/share_workspace.py
  parsec/core/fs/userfs/userfs.py
  parsec/core/fs/workspacefs/workspacefs.py
  parsec/test_utils/organization.py
  src/api_crypto.rs
  src/enumerate.rs
  src/protocol/error.rs
  src/protocol/realm.rs
  tests/backend/organization/test_stats.py
  tests/backend/realm/test_block.py
  tests/backend/realm/test_reencryption_maintenance.py
  tests/backend/realm/test_roles.py
  tests/backend/realm/test_shuffle_roles.py
  tests/backend/realm/test_vlob_access.py
  tests/backend/test_administration_rest_api.py
  tests/backend/user/test_user_create.py
  tests/core/fs/userfs/test_sharing.py
Labels: enhancement, python, rust

#3793 Fix parsec-extensions
  parsec/core/local_device.py
Labels: python

#3629 Add sequester crypto
  .cspell/custom-words.txt
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  build.py
  oxidation/bindings/common/Cargo.toml
  oxidation/libparsec/Cargo.toml
  oxidation/libparsec/crates/client_connection/Cargo.toml
  oxidation/libparsec/crates/client_types/Cargo.toml
  oxidation/libparsec/crates/core/Cargo.toml
  oxidation/libparsec/crates/core_fs/Cargo.toml
  oxidation/libparsec/crates/crypto/Cargo.toml
  oxidation/libparsec/crates/crypto/src/common/error.rs
  oxidation/libparsec/crates/crypto/src/common/mod.rs
  oxidation/libparsec/crates/crypto/src/common/secret.rs
  oxidation/libparsec/crates/crypto/src/common/sequester.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/mod.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/secret.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/sequester.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/sign.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/mod.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/secret.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/sequester.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/sign.rs
  oxidation/libparsec/crates/crypto/src/traits.rs
  oxidation/libparsec/crates/crypto/tests/secret.rs
  oxidation/libparsec/crates/crypto/tests/sequester.rs
  oxidation/libparsec/crates/crypto/tests/sign.rs
  oxidation/libparsec/crates/protocol/Cargo.toml
  oxidation/libparsec/crates/serialization_format/src/utils.rs
  oxidation/libparsec/crates/tests_fixtures/Cargo.toml
  oxidation/libparsec/crates/types/Cargo.toml
  parsec/__init__.py
  parsec/_parsec.pyi
  parsec/_parsec_pyi/crypto.pyi
  parsec/api/data/certif.py
  parsec/backend/cli/sequester.py
  parsec/backend/organization.py
  parsec/backend/postgresql/organization.py
  parsec/backend/postgresql/sequester.py
  parsec/core/cli/bootstrap_organization.py
  parsec/core/invite/organization.py
  parsec/sequester_crypto.py
  parsec/sequester_export_reader.py
  parsec/serde/fields.py
  poetry.lock
  pyproject.toml
  src/api_crypto.rs
  src/lib.rs
  tests/backend/sequester/test_crypto.py
  tests/backend/sequester/test_export.py
  tests/common/sequester.py
  tests/core/fs/test_sequester.py
  tests/core/test_bootstrap_organization.py
  tests/schemas/api_data.json
  tests/test_cli.py
Labels: refactor, python, rust

#3636 Oxidation add sequester certif
  newsfragments/3639.empty.rst
  newsfragments/3640.empty.rst
  oxidation/generate_test_data/certif.py
  oxidation/generate_test_data/protocol/utils.py
  oxidation/libparsec/crates/types/schema/certif/sequester_authority_certificate.json
  oxidation/libparsec/crates/types/schema/certif/sequester_service_certificate.json
  oxidation/libparsec/crates/types/src/certif.rs
  oxidation/libparsec/crates/types/src/error.rs
  oxidation/libparsec/crates/types/tests/test_certif.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/certif.pyi
  parsec/api/data/__init__.py
  parsec/api/data/certif.py
  parsec/backend/organization.py
  parsec/core/fs/remote_loader.py
  parsec/core/invite/organization.py
  src/data/certif.rs
  src/data/mod.rs
  tests/common/sequester.py
  tests/schemas/api_data.json
  tests/schemas/builder.py
  tests/schemas/test_compat.py
Labels: refactor, python, rust

#3794 Remove SequesterServiceIDField
  parsec/api/protocol/__init__.py
  parsec/api/protocol/sequester.py
  parsec/backend/postgresql/vlob.py
  parsec/backend/postgresql/vlob_queries/write.py
Labels: python

#3645 Remove sequester key field
  parsec/serde/fields.py
Labels: python

#3646 Remove base data
  parsec/api/data/__init__.py
  parsec/api/data/base.py
  tests/schemas/builder.py
Labels: python

#3795 Remove backend organization addr field
  parsec/core/types/__init__.py
  parsec/core/types/backend_address.py
Labels: python
