Repository Scille/parsec-cloud, pull requests merged in 2022-11, with the labels that each got.

#3433 mypy: Added mypy typing to `core.gui.lang`
  mypy.ini
  parsec/core/gui/lang.py
Labels: python

#3441 Bump pre-commit
  .pre-commit-config.yaml
Labels: enhancement

#3427 Yolo enhance crypto impl
  oxidation/bindings/common/src/lib.rs
  oxidation/libparsec/crates/client_types/src/local_device.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/src/local_manifest.rs
  oxidation/libparsec/crates/client_types/tests/test_local_manifest.rs
  oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/user_storage.rs
  oxidation/libparsec/crates/crypto/src/common/error.rs
  oxidation/libparsec/crates/crypto/src/common/mod.rs
  oxidation/libparsec/crates/crypto/src/common/secret.rs
  oxidation/libparsec/crates/crypto/src/lib.rs
  oxidation/libparsec/crates/crypto/src/macros.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/private.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/secret.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/sign.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/private.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/secret.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/sign.rs
  oxidation/libparsec/crates/crypto/tests/private.rs
  oxidation/libparsec/crates/crypto/tests/secret.rs
  oxidation/libparsec/crates/tests_fixtures/src/lib.rs
  oxidation/libparsec/crates/types/src/invite.rs
  oxidation/libparsec/crates/types/src/manifest.rs
  src/api_crypto.rs
Labels: refactor, rust

#3448 Mypy gui password
  mypy.ini
  newsfragments/3447.empty.rst
  parsec/core/gui/password_authentication_widget.py
  parsec/core/gui/password_validation.py
  parsec/stubs/zxcvbn/__init__.pyi
  parsec/stubs/zxcvbn/py.typed
Labels: enhancement, python

#3450 Mypy gui settings
  mypy.ini
  newsfragments/3449.empty.rst
  parsec/core/gui/settings_dialog.py
  parsec/core/gui/settings_widget.py
Labels: enhancement, python

#3443 Mypy gui organization info widget
  mypy.ini
  newsfragments/3442.empty.rst
  parsec/core/gui/organization_info_widget.py
Labels: enhancement, python

#3446 Mypy gui parsec application
  mypy.ini
  newsfragments/3444.empty.rst
  parsec/core/gui/parsec_application.py
Labels: enhancement, python

#3485 Mypy gui app
  mypy.ini
  newsfragments/3483.empty.rst
  parsec/core/gui/app.py
Labels: enhancement, python

#3438 mypy: Added mypy typing for `instance_widget`
  mypy.ini
  parsec/core/gui/instance_widget.py
  parsec/core/gui/main_window.py
Labels: enhancement, python

#3454 Add mypy typing to `core.gui.file[s]*`
  mypy.ini
  parsec/core/gui/file_history_widget.py
  parsec/core/gui/file_items.py
  parsec/core/gui/file_size.py
  parsec/core/gui/file_status_widget.py
  parsec/core/gui/file_table.py
  parsec/core/gui/files_widget.py
Labels: enhancement, python

#3393 mypy: Added mypy typing for`greet_device_widget` and `greet_user_widget`
  mypy.ini
  newsfragments/3353.empty.rst
  parsec/core/gui/greet_device_widget.py
  parsec/core/gui/greet_user_widget.py
Labels: enhancement, python

#3428 Add mypy typing `parse.core.gui.device[s]*`
  mypy.ini
  parsec/core/gui/claim_user_widget.py
  parsec/core/gui/device_recovery_export_widget.py
  parsec/core/gui/device_recovery_import_widget.py
  parsec/core/gui/devices_widget.py
  parsec/core/gui/main_window.py
Labels: enhancement, python

#3439 Mypy gui notification
  mypy.ini
  newsfragments/3436.empty.rst
  parsec/core/gui/notification_center_widget.py
  parsec/core/gui/notification_widget.py
Labels: enhancement, python

#3510 Bump rust to version 1.65.0
  .github/workflows/ci.yml
  .github/workflows/package-ci.yml
  docs/development/quickstart.rst
  misc/setup-rust.sh
  oxidation/bindings/electron/src/meths.rs
  oxidation/bindings/generator/templates/binding_electron_meths.rs.j2
  oxidation/libparsec/crates/client_connection/tests/utils/server.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  rust-toolchain.toml
  src/certif.rs
  src/protocol/invite.rs
Labels: enhancement, rust

#3509 Fix invite without human handle
  newsfragments/3507.bugfix.rst
  src/protocol/invite.rs
Labels: rust

#3504 Fix import
  parsec/core/gui/claim_user_widget.py
Labels: python

#3221 Replace UserProfile
  newsfragments/3235.empty.rst
  parsec/_parsec.pyi
  parsec/_parsec_pyi/addrs.pyi
  parsec/_parsec_pyi/certif.pyi
  parsec/_parsec_pyi/enumerate.pyi
  parsec/_parsec_pyi/invite.pyi
  parsec/_parsec_pyi/local_device.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/_parsec_pyi/time.pyi
  parsec/api/protocol/__init__.py
  parsec/api/protocol/handshake.py
  parsec/api/protocol/invite.py
  parsec/api/protocol/types.py
  parsec/backend/memory/organization.py
  parsec/backend/postgresql/organization.py
  parsec/backend/postgresql/pki.py
  parsec/backend/postgresql/realm_queries/update_roles.py
  parsec/backend/postgresql/user_queries/create.py
  parsec/backend/postgresql/user_queries/get.py
  parsec/core/cli/invitation.py
  parsec/serde/fields.py
  parsec/test_utils/organization.py
  src/addrs.rs
  src/binding_utils.rs
  src/certif.rs
  src/enumerate.rs
  src/invite.rs
  src/lib.rs
  src/local_device.rs
  src/manifest.rs
  src/protocol/events.rs
  src/protocol/invite.rs
  src/protocol/organization.rs
  tests/api/test_data_certif.py
  tests/backend/organization/test_stats.py
  tests/backend/test_administration_rest_api.py
  tests/backend/user/test_user_create.py
  tests/core/test_local_device.py
  tests/schemas/api_data.json
Labels: refactor, python, rust

#3219 Oxidation replace message
  newsfragments/3218.empty.rst
  oxidation/libparsec/crates/types/src/message.rs
  oxidation/libparsec/crates/types/tests/test_message.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/message.pyi
  parsec/api/data/__init__.py
  parsec/api/data/message.py
  parsec/core/fs/userfs/userfs.py
  src/binding_utils.rs
  src/lib.rs
  src/message.rs
  src/protocol/mod.rs
  tests/schemas/api_data.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#3549 Mypy sequester export reader
  mypy.ini
  newsfragments/3544.empty.rst
  parsec/sequester_export_reader.py
Labels: enhancement, python

#3430 Oxidation api crypto
  Cargo.lock
  newsfragments/3429.empty.rst
  oxidation/generate_test_data/local_file_device.py
  oxidation/libparsec/crates/crypto/Cargo.toml
  oxidation/libparsec/crates/crypto/src/rustcrypto/mod.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/secret.rs
  oxidation/libparsec/crates/crypto/src/rustcrypto/utils.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/mod.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/secret.rs
  oxidation/libparsec/crates/crypto/src/sodiumoxide/utils.rs
  oxidation/libparsec/crates/crypto/tests/secret.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/addrs.pyi
  parsec/_parsec_pyi/crypto.pyi
  parsec/core/gui/device_recovery_import_widget.py
  parsec/core/invite/claimer.py
  parsec/core/invite/greeter.py
  parsec/core/local_device.py
  parsec/crypto.py
  src/addrs.rs
  src/api_crypto.rs
  src/invite.rs
  src/lib.rs
  src/local_manifest.rs
  tests/core/test_recovery.py
  tests/test_types.py
Labels: refactor, python, rust

#3558 Oxidation refactor UUID
  oxidation/libparsec/crates/client_types/tests/test_local_manifest.rs
  oxidation/libparsec/crates/protocol/tests/test_block.rs
  oxidation/libparsec/crates/protocol/tests/test_events.rs
  oxidation/libparsec/crates/protocol/tests/test_handshake.rs
  oxidation/libparsec/crates/protocol/tests/test_invite.rs
  oxidation/libparsec/crates/protocol/tests/test_realm.rs
  oxidation/libparsec/crates/protocol/tests/test_vlob.rs
  oxidation/libparsec/crates/tests_fixtures/src/lib.rs
  oxidation/libparsec/crates/types/src/addr.rs
  oxidation/libparsec/crates/types/src/ext_types.rs
  oxidation/libparsec/crates/types/src/id.rs
  oxidation/libparsec/crates/types/src/invite.rs
  oxidation/libparsec/crates/types/src/manifest.rs
  oxidation/libparsec/crates/types/tests/test_certif.rs
  oxidation/libparsec/crates/types/tests/test_manifest.rs
  oxidation/libparsec/crates/types/tests/test_message.rs
  parsec/_parsec_pyi/ids.pyi
  parsec/backend/cli/sequester.py
  parsec/backend/memory/block.py
  parsec/backend/memory/realm.py
  parsec/backend/memory/vlob.py
  parsec/backend/postgresql/realm_queries/get.py
  parsec/backend/postgresql/realm_queries/maintenance.py
  parsec/backend/postgresql/realm_queries/update_roles.py
  parsec/backend/postgresql/sequester.py
  parsec/backend/postgresql/sequester_export.py
  parsec/backend/postgresql/vlob_queries/read.py
  parsec/backend/postgresql/vlob_queries/utils.py
  parsec/backend/postgresql/vlob_queries/write.py
  parsec/backend/raid1_blockstore.py
  parsec/backend/raid5_blockstore.py
  parsec/backend/s3_blockstore.py
  parsec/backend/swift_blockstore.py
  parsec/backend/vlob.py
  parsec/core/config.py
  parsec/core/fs/remote_loader.py
  parsec/core/fs/storage/version.py
  parsec/core/fs/storage/workspace_storage.py
  parsec/core/fs/userfs/userfs.py
  parsec/core/fs/workspacefs/workspacefs.py
  parsec/core/mountpoint/manager.py
  parsec/core/mountpoint/winfsp_runner.py
  parsec/core/sync_monitor.py
  src/addrs.rs
  src/ids.rs
  src/invite.rs
  src/lib.rs
  src/protocol/events.rs
  src/protocol/invite.rs
  tests/backend/realm/test_block.py
  tests/backend/realm/test_reencryption_maintenance.py
  tests/backend/realm/test_vlob_access.py
  tests/backend/sequester/test_vlob.py
  tests/backend/test_s3_blockstore.py
  tests/backend/test_swift_blockstore.py
  tests/core/fs/storage/test_workspace_storage.py
  tests/core/fs/workspacefs/test_workspace_fs.py
  tests/core/fs/workspacefs_timestamped/test_workspacefs.py
  tests/core/mountpoint/test_base.py
  tests/test_cli.py
Labels: enhancement, refactor, python, rust

#3561 Remove require_greeter_timestamp_rep_dump
  parsec/api/protocol/base.py
Labels: enhancement, python

#3551 Update `actions/setup-python` to `v4.3.0`
  .github/actions/setup-python-poetry/action.yml
Labels: ci, dependencies

#3552 Use `dtolnay/rust-toolchain` instead of `actions-rs/toolchain`
  .github/workflows/package-ci.yml
Labels: ci, dependencies

#3222 Oxidation replace pki
  newsfragments/3236.empty.rst
  oxidation/libparsec/crates/types/schema/pki/pki_enrollment_answer_payload.json
  oxidation/libparsec/crates/types/schema/pki/pki_enrollment_submit_payload.json
  oxidation/libparsec/crates/types/src/lib.rs
  oxidation/libparsec/crates/types/src/pki.rs
  oxidation/libparsec/crates/types/tests/mod.rs
  oxidation/libparsec/crates/types/tests/test_pki.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/pki.pyi
  parsec/api/data/__init__.py
  parsec/api/data/pki.py
  parsec/backend/pki.py
  parsec/core/pki/accepter.py
  parsec/core/pki/plumbing.py
  parsec/core/pki/submitter.py
  parsec/core/types/pki.py
  parsec/serde/fields.py
  src/data/mod.rs
  src/data/pki.rs
  src/lib.rs
  tests/backend/test_pki.py
  tests/common/smartcard.py
  tests/fixtures.py
  tests/schemas/api_data.json
  tests/schemas/core_data.json
Labels: refactor, python, rust

#3559 Add EnrollmentID
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_accept.json5
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_info.json5
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_list.json5
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_reject.json5
  oxidation/libparsec/crates/serialization_format/src/protocol/utils.rs
  oxidation/libparsec/crates/types/src/id.rs
  oxidation/libparsec/crates/types/src/lib.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/ids.pyi
  src/ids.rs
Labels: python, rust

#3574 Oxidation update invite enum
  newsfragments/3232.empty.rst
  oxidation/generate_test_data/protocol/invite.py
  parsec/_parsec.pyi
  parsec/_parsec_pyi/enumerate.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/invite.py
  parsec/backend/postgresql/invite.py
  parsec/core/cli/invitation.py
  parsec/core/invite/greeter.py
  parsec/core/logged_core.py
  src/enumerate.rs
  src/lib.rs
  src/protocol/events.rs
  src/protocol/invite.rs
  tests/backend/invite/test_manage_invitations.py
Labels: refactor, python, rust

#3572 Update InvitationToken
  parsec/_parsec.pyi
  parsec/_parsec_pyi/addrs.pyi
  parsec/_parsec_pyi/ids.pyi
  parsec/_parsec_pyi/invite.pyi
  parsec/_parsec_pyi/protocol.pyi
Labels: enhancement, python

#3576 Remove pki enrollment status field
  newsfragments/3575.empty.rst
  parsec/api/protocol/__init__.py
  parsec/api/protocol/pki.py
Labels: python

#3584 Oxidation client type
  newsfragments/3583.empty.rst
  oxidation/libparsec/crates/client_types/src/lib.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/enumerate.pyi
  parsec/api/protocol/base.py
  parsec/backend/app.py
  parsec/backend/asgi/rpc.py
  parsec/backend/client_context.py
  parsec/backend/invite.py
  parsec/backend/organization.py
  parsec/backend/ping.py
  parsec/backend/pki.py
  parsec/backend/utils.py
  src/enumerate.rs
  src/lib.rs
  tests/core/backend_connection/test_authenticated_cmds.py
  tests/core/backend_connection/test_authenticated_conn.py
Labels: refactor, python, rust

#3590 Add protocol schema anonymous
  oxidation/generate_test_data/protocol/pki.py
  oxidation/libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_info.json5
  oxidation/libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_submit.json5
  oxidation/libparsec/crates/protocol/src/lib.rs
  oxidation/libparsec/crates/protocol/tests/mod.rs
  oxidation/libparsec/crates/protocol/tests/test_pki.rs
  src/protocol/cmds.rs
Labels: enhancement

#3587 Oxidation remove UUID
  oxidation/libparsec/crates/types/src/addr.rs
  oxidation/libparsec/crates/types/src/id.rs
  oxidation/libparsec/crates/types/tests/test_manifest.rs
  parsec/_parsec_pyi/ids.pyi
  parsec/backend/cli/sequester.py
  parsec/backend/postgresql/block.py
  parsec/backend/postgresql/handler.py
  parsec/backend/postgresql/invite.py
  parsec/backend/postgresql/pki.py
  parsec/backend/postgresql/realm_queries/create.py
  parsec/backend/postgresql/realm_queries/get.py
  parsec/backend/postgresql/realm_queries/maintenance.py
  parsec/backend/postgresql/realm_queries/update_roles.py
  parsec/backend/postgresql/sequester.py
  parsec/backend/postgresql/sequester_export.py
  parsec/backend/postgresql/vlob_queries/maintenance.py
  parsec/backend/postgresql/vlob_queries/read.py
  parsec/backend/postgresql/vlob_queries/utils.py
  parsec/backend/postgresql/vlob_queries/write.py
  parsec/backend/raid0_blockstore.py
  parsec/backend/s3_blockstore.py
  parsec/backend/swift_blockstore.py
  parsec/core/backend_connection/authenticated.py
  parsec/core/fs/remote_loader.py
  parsec/core/fs/storage/workspace_storage.py
  parsec/core/fs/userfs/userfs.py
  parsec/core/fs/workspacefs/workspacefs.py
  parsec/core/mountpoint/winfsp_operations.py
  parsec/core/pki/accepter.py
  parsec/core/sync_monitor.py
  parsec/sequester_export_reader.py
  parsec/serde/fields.py
  src/ids.rs
  tests/backend/sequester/test_export.py
  tests/backend/test_postgres_db.py
  tests/common/binder.py
  tests/core/backend_connection/test_authenticated_conn.py
  tests/core/fs/test_reencrypt_workspace.py
  tests/core/fs/test_sequester.py
  tests/core/fs/userfs/test_invalid_data.py
  tests/core/fs/userfs/test_sharing.py
  tests/core/fs/workspacefs/test_invalid_data.py
  tests/core/fs/workspacefs/test_workspace_fs.py
  tests/core/fs/workspacefs/test_workspace_reencryption_need.py
  tests/core/test_sync_monitor.py
  tests/fixtures.py
Labels: enhancement, python, rust

#3598 Add EnrollmentID
  oxidation/generate_test_data/protocol/pki.py
  parsec/api/data/__init__.py
  parsec/api/protocol/__init__.py
  parsec/api/protocol/pki.py
  parsec/backend/memory/pki.py
  parsec/backend/pki.py
  parsec/backend/postgresql/pki.py
  parsec/core/backend_connection/anonymous.py
  parsec/core/backend_connection/cmds.py
  parsec/core/cli/pki.py
  parsec/core/pki/accepter.py
  parsec/core/pki/plumbing.py
  parsec/core/pki/submitter.py
  parsec/core/types/__init__.py
  parsec/core/types/pki.py
  src/lib.rs
  tests/backend/test_pki.py
  tests/backend/test_postgres_concurrency.py
  tests/common/smartcard.py
  tests/fixtures.py
  tests/schemas/api_protocol.json
  tests/schemas/core_data.json
Labels: python

#3600 Split libparsec
  src/data/certif.rs
  src/data/invite.rs
  src/data/local_manifest.rs
  src/data/manifest.rs
  src/data/message.rs
  src/data/mod.rs
  src/file_operations.rs
  src/lib.rs
  src/protocol/mod.rs
  src/trustchain.rs
Labels: enhancement, rust

#3609 Use updated `samuelmeuli/action-snapcraft` to use `node-16`
  .github/workflows/package-ci.yml
Labels: ci, github_actions

#3610 Update `dtolnay/rust-toolchain` action used by `package-android-app`
  .github/workflows/package-ci.yml
Labels: ci, github_actions

#3608 [GUI] Fixed pyqtsignal typing for claim/greet
  parsec/core/gui/claim_device_widget.py
  parsec/core/gui/claim_user_widget.py
  parsec/core/gui/greet_device_widget.py
  parsec/core/gui/greet_user_widget.py
Labels: docs, python

#3606 Oxidation replace data error
  oxidation/libparsec/crates/client_types/src/local_manifest.rs
  oxidation/libparsec/crates/core/src/trustchain.rs
  oxidation/libparsec/crates/types/src/certif.rs
  oxidation/libparsec/crates/types/src/error.rs
  oxidation/libparsec/crates/types/src/manifest.rs
  oxidation/libparsec/crates/types/tests/test_certif.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/__init__.pyi
  parsec/api/data/__init__.py
  parsec/api/data/base.py
  parsec/api/data/entry.py
  parsec/core/fs/path.py
  parsec/core/fs/workspacefs/sync_transactions.py
  src/binding_utils.rs
  src/data/certif.rs
  src/data/error.rs
  src/data/local_manifest.rs
  src/data/manifest.rs
  src/data/mod.rs
  src/data/pki.rs
  tests/api/test_types.py
Labels: refactor, python, rust

#3585 Oxidation authenticated pki protocol
  oxidation/generate_test_data/protocol/pki.py
  oxidation/libparsec/crates/protocol/tests/test_pki.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/pki.py
  parsec/backend/memory/pki.py
  parsec/backend/pki.py
  parsec/core/backend_connection/cmds.py
  parsec/core/cli/pki.py
  parsec/core/pki/accepter.py
  parsec/core/types/pki.py
  src/protocol/cmds.rs
  src/protocol/mod.rs
  src/protocol/pki.rs
  tests/backend/common.py
  tests/backend/test_pki.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#3630 Add stubs file `msgpack`
  parsec/serde/packing.py
  parsec/stubs/msgpack/__init__.pyi
  parsec/stubs/msgpack/exceptions/__init__.pyi
  parsec/stubs/msgpack/py.typed
Labels: enhancement, python

#3626 Oxidize pki anonymous commands
  oxidation/libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_submit.json5
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/base.py
  parsec/api/protocol/pki.py
  parsec/backend/memory/pki.py
  parsec/backend/pki.py
  parsec/backend/postgresql/pki.py
  parsec/backend/utils.py
  parsec/core/backend_connection/anonymous.py
  parsec/core/backend_connection/cmds.py
  parsec/core/pki/accepter.py
  parsec/core/pki/submitter.py
  src/protocol/cmds.rs
  src/protocol/mod.rs
  src/protocol/pki.rs
  tests/backend/common.py
  tests/backend/test_pki.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: python, rust

#3631 Split `protocol.pyi` into submodules
  parsec/_parsec_pyi/protocol.pyi
  parsec/_parsec_pyi/protocol/__init__.pyi
  parsec/_parsec_pyi/protocol/block.pyi
  parsec/_parsec_pyi/protocol/cmd.pyi
  parsec/_parsec_pyi/protocol/events.pyi
  parsec/_parsec_pyi/protocol/invite.pyi
  parsec/_parsec_pyi/protocol/message.pyi
  parsec/_parsec_pyi/protocol/organization.pyi
  parsec/_parsec_pyi/protocol/ping.pyi
  parsec/_parsec_pyi/protocol/pki.pyi
  parsec/_parsec_pyi/protocol/realm.pyi
  parsec/_parsec_pyi/protocol/user.pyi
  parsec/_parsec_pyi/protocol/vlob.pyi
Labels: refactor, python
