Repository Scille/parsec-cloud, pull requests merged in 2022-09, with the labels that each got.

#2997 Ignore news fragment in branch starting with `revert`
  .github/workflows/ci.yml
Labels: enhancement, ci

#2544 Feat/authenticated api server
  newsfragments/2624.feature.rst
  newsfragments/2979.bugfix.rst
  oxidation/libparsec/crates/crypto/src/rustcrypto/sign.rs
  oxidation/libparsec/crates/types/src/time.rs
  parsec/_parsec_pyi/crypto.pyi
  parsec/_parsec_pyi/time.pyi
  parsec/api/protocol/__init__.py
  parsec/api/protocol/base.py
  parsec/api/protocol/handshake.py
  parsec/api/version.py
  parsec/backend/asgi/rpc.py
  parsec/backend/handshake.py
  parsec/core/backend_connection/anonymous.py
  parsec/core/gui/central_widget.py
  src/api_crypto.rs
  tests/api/test_apiv1_handshake.py
  tests/api/test_handshake.py
  tests/backend/test_rpc_handshake.py
  tests/backend/test_ws_handshake.py
  tests/common/__init__.py
  tests/common/backend.py
  tests/common/rpc_api.py
  tests/core/backend_connection/test_invited_cmds.py
  tests/core/test_sync_monitor_stateful.py
Labels: python

#2998 Oxidation replace protocol vlob
  newsfragments/3000.empty.rst
  oxidation/generate_test_data/protocol/vlob.py
  oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_create.json
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_update.json
  oxidation/libparsec/crates/protocol/tests/test_vlob.rs
  oxidation/libparsec/crates/serialization_format/src/parser/protocol.rs
  oxidation/libparsec/crates/serialization_format/src/parser/utils.rs
  oxidation/libparsec/crates/types/src/manifest.rs
  oxidation/libparsec/crates/types/src/time.rs
  oxidation/libparsec_python/libparsec/types.py
  oxidation/libparsec_python/src/lib.rs
  oxidation/libparsec_python/src/protocol/events.rs
  oxidation/libparsec_python/src/protocol/invite.rs
  oxidation/libparsec_python/src/protocol/message.rs
  oxidation/libparsec_python/src/protocol/mod.rs
  oxidation/libparsec_python/src/protocol/organization.rs
  oxidation/libparsec_python/src/protocol/ping.rs
  oxidation/libparsec_python/src/protocol/realm.rs
  oxidation/libparsec_python/src/protocol/user.rs
  oxidation/libparsec_python/src/protocol/vlob.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/ids.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/_parsec_pyi/time.pyi
  parsec/api/data/__init__.py
  parsec/api/protocol/__init__.py
  parsec/api/protocol/base.py
  parsec/api/protocol/block.py
  parsec/api/protocol/sequester.py
  parsec/api/protocol/vlob.py
  parsec/backend/vlob.py
  parsec/core/backend_connection/cmds.py
  parsec/core/fs/remote_loader.py
  parsec/core/fs/userfs/userfs.py
  parsec/core/gui/workspaces_widget.py
  parsec/core/sync_monitor.py
  src/ids.rs
  src/invite.rs
  src/lib.rs
  src/local_manifest.rs
  src/manifest.rs
  src/protocol/cmds.rs
  src/protocol/mod.rs
  src/protocol/vlob.rs
  src/time.rs
  tests/backend/common.py
  tests/backend/realm/test_reencryption_maintenance.py
  tests/backend/realm/test_roles.py
  tests/backend/realm/test_vlob_access.py
  tests/backend/realm/test_vlob_poll_changes.py
  tests/backend/sequester/test_vlob.py
  tests/core/fs/test_fs_sync.py
  tests/core/fs/workspacefs/test_workspace_fs.py
  tests/core/fs/workspacefs_timestamped/test_workspacefs.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#3010 Oxidation replace protocol message
  newsfragments/3009.empty.rst
  oxidation/libparsec_python/libparsec/types.py
  oxidation/libparsec_python/src/lib.rs
  oxidation/libparsec_python/src/protocol/message.rs
  oxidation/libparsec_python/src/protocol/mod.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/message.py
  parsec/backend/message.py
  parsec/core/backend_connection/cmds.py
  parsec/core/fs/userfs/userfs.py
  src/lib.rs
  src/protocol/cmds.rs
  src/protocol/message.rs
  src/protocol/mod.rs
  tests/backend/common.py
  tests/backend/realm/test_reencryption_maintenance.py
  tests/backend/test_message.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#2956 Update configuration for `editorconfig` + update dev documentation
  .editorconfig
  .gitignore
  docs/development/quickstart.rst
  poetry.lock
  pyproject.toml
Labels: docs

#3017 Oxidation remove clippy allow pyo3
  newsfragments/2863.empty.rst
  oxidation/libparsec_python/src/lib.rs
  src/lib.rs
Labels: rust

#3015 Remove `restore-keys` in actions `setup-rust`
  .github/actions/setup-rust/action.yml
Labels: enhancement, ci

#3016 Oxidation replace protocol organization
  newsfragments/3012.empty.rst
  oxidation/generate_test_data/protocol/organization.py
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/organization_config.json
  oxidation/libparsec/crates/protocol/tests/test_organization.rs
  oxidation/libparsec_python/libparsec/types.py
  oxidation/libparsec_python/src/lib.rs
  oxidation/libparsec_python/src/protocol/mod.rs
  oxidation/libparsec_python/src/protocol/organization.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/__init__.py
  parsec/api/protocol/organization.py
  parsec/backend/organization.py
  parsec/core/backend_connection/authenticated.py
  parsec/core/backend_connection/cmds.py
  parsec/core/logged_core.py
  parsec/core/types/organizations.py
  src/lib.rs
  src/protocol/cmds.rs
  src/protocol/mod.rs
  src/protocol/organization.rs
  tests/backend/common.py
  tests/backend/organization/test_config.py
  tests/backend/organization/test_stats.py
  tests/core/test_logged_core.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#3034 Migrate to `poetry-1.2.0`
  .github/workflows/ci.yml
  .github/workflows/package-ci.yml
  docs/development/quickstart.rst
  newsfragments/3033.empty.rst
Labels: ci, docs

#3008 Add script to wipe Github Cache entries.
  .github/scripts/sink_cache.py
Labels: ci, python, github_actions

#3048 Oxidation replace protocol realm
  newsfragments/3045.empty.rst
  oxidation/generate_test_data/protocol/realm.py
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_create.json
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_start_reencryption_maintenance.json
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_update_roles.json
  oxidation/libparsec/crates/protocol/tests/test_realm.rs
  oxidation/libparsec_python/libparsec/types.py
  oxidation/libparsec_python/src/lib.rs
  oxidation/libparsec_python/src/protocol/mod.rs
  oxidation/libparsec_python/src/protocol/realm.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/__init__.py
  parsec/api/protocol/realm.py
  parsec/backend/memory/realm.py
  parsec/backend/realm.py
  parsec/core/backend_connection/cmds.py
  parsec/core/fs/remote_loader.py
  parsec/core/fs/userfs/userfs.py
  parsec/core/fs/workspacefs/workspacefs.py
  src/lib.rs
  src/protocol/cmds.rs
  src/protocol/mod.rs
  src/protocol/realm.rs
  tests/backend/common.py
  tests/backend/realm/test_base.py
  tests/backend/realm/test_create.py
  tests/backend/realm/test_realm_stats.py
  tests/backend/realm/test_reencryption_maintenance.py
  tests/backend/realm/test_roles.py
  tests/backend/realm/test_roles_updated_event.py
  tests/backend/realm/test_shuffle_roles.py
  tests/backend/realm/test_vlob_access.py
  tests/backend/realm/test_vlob_poll_changes.py
  tests/backend/test_compatibility.py
  tests/core/fs/userfs/test_sharing.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#1852 Add a way to hide unmounted workspaces
  newsfragments/3056.feature.rst
  parsec/core/gui/forms/workspaces_widget.ui
  parsec/core/gui/tr/parsec_en.po
  parsec/core/gui/tr/parsec_fr.po
  parsec/core/gui/workspace_button.py
  parsec/core/gui/workspaces_widget.py
  tests/core/gui/conftest.py
  tests/core/gui/test_files.py
  tests/core/gui/test_workspaces.py
Labels: enhancement, gui, stale

#3004 Oxidation replace protocol ping
  newsfragments/3003.empty.rst
  oxidation/generate_test_data/protocol/ping.py
  oxidation/libparsec_python/libparsec/types.py
  oxidation/libparsec_python/src/lib.rs
  oxidation/libparsec_python/src/protocol/mod.rs
  oxidation/libparsec_python/src/protocol/ping.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/__init__.py
  parsec/api/protocol/base.py
  parsec/api/protocol/cmds.py
  parsec/api/protocol/ping.py
  parsec/backend/asgi/ws.py
  parsec/backend/ping.py
  parsec/core/backend_connection/apiv1_annonymous.py
  parsec/core/backend_connection/authenticated.py
  parsec/core/backend_connection/cmds.py
  parsec/core/backend_connection/invited.py
  src/lib.rs
  src/protocol/cmds.rs
  src/protocol/mod.rs
  src/protocol/ping.rs
  tests/backend/common.py
  tests/backend/test_apiv1_organization_bootstrap.py
  tests/backend/test_events.py
  tests/backend/user/test_device_create.py
  tests/backend/user/test_user_revoke.py
  tests/common/rpc_api.py
  tests/core/backend_connection/test_apiv1_anonymous_cmds.py
  tests/core/backend_connection/test_authenticated_cmds.py
  tests/core/backend_connection/test_authenticated_conn.py
  tests/core/backend_connection/test_invited_cmds.py
  tests/core/backend_connection/test_keepalive.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#3058 Revert log change for response status
  parsec/backend/asgi/ws.py
Labels: python

#3061 Add test showcasing oxidized list_available_devices failing to load r…
  newsfragments/3062.empty.rst
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/tests/test_local_device_file.rs
Labels: rust

#3001 Add `github.job` to segregate rust cache per job
  .github/workflows/ci.yml
Labels: enhancement, ci

#3055 Add job to run tests with WasmPack
  .github/actions/setup-rust/action.yml
  .github/workflows/ci.yml
  .yamllint.yml
Labels: ci, rust, Ionic

#3073 Impl `Debug` & `Display` for `LocalDateTime`
  oxidation/libparsec/crates/types/src/time.rs
  src/time.rs
Labels: enhancement, python, rust

#3069 Rewrite dev documentation for the Ionic client.
  oxidation/client/README.md
Labels: refactor, docs, Ionic

#3079 Chore clean binding_utils & use on manifest
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  build.py
  newsfragments/3080.empty.rst
  newsfragments/3081.empty.rst
  oxidation/libparsec/crates/types/src/manifest.rs
  src/addrs.rs
  src/binding_utils.rs
  src/ids.rs
  src/invite.rs
  src/manifest.rs
  src/time.rs
Labels: enhancement, rust

#3104 Rework npm script to build electron app in release mode
  .github/workflows/package-ci.yml
  newsfragments/3100.empty.rst
  oxidation/client/package.json
Labels: ci, refactor, Ionic

#3068 Add job to build Unsigned APK file for Android
  .github/workflows/package-ci.yml
  newsfragments/2873.empty.rst
  oxidation/client/package.json
Labels: ci, Ionic

#3101 Remove `Azure Pipeline file`
  .azure-pipelines.yml
  ci/cache-rust.yml
Labels: ci

#3043 Access log enhancement
  newsfragments/2953.empty.rst
  parsec/backend/asgi/__init__.py
  parsec/backend/asgi/logger.py
  parsec/backend/ping.py
  tests/backend/test_logger.py
  tests/common/backend.py
Labels: enhancement, python

#3117 Oxidation use gen proto addrs
  newsfragments/3086.empty.rst
  newsfragments/3087.empty.rst
  oxidation/libparsec/crates/types/src/addr.rs
  oxidation/libparsec/crates/types/src/invite.rs
  src/addrs.rs
Labels: rust

#3116 Oxidation use gen proto certif
  newsfragments/3090.empty.rst
  newsfragments/3091.empty.rst
  src/certif.rs
Labels: rust

#3115 Oxidation use gen proto ids
  newsfragments/3092.empty.rst
  newsfragments/3093.empty.rst
  src/ids.rs
Labels: rust

#3118 Oxiddation use gen proto invite
  newsfragments/3094.empty.rst
  newsfragments/3095.empty.rst
  oxidation/libparsec/crates/types/src/invite.rs
  src/invite.rs
Labels: rust

#3113 Oxidation use gen proto local device
  newsfragments/3096.empty.rst
  newsfragments/3097.empty.rst
  src/local_device.rs
Labels: rust

#3111 Oxidation use gen proto time
  newsfragments/3098.empty.rst
  newsfragments/3099.empty.rst
  src/time.rs
Labels: rust

#3138 Disable fail-fast on CI
  .github/workflows/ci.yml
Labels: enhancement, ci

#3140 Force maturin to use venv Python interpreter
  build.py
Labels: bug, python

#3129 Oxidation replace event protocol
  newsfragments/3047.empty.rst
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/events_listen.json
  oxidation/libparsec/crates/protocol/tests/test_events.rs
  oxidation/libparsec_python/src/protocol/events.rs
  oxidation/libparsec_python/src/protocol/mod.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/base.py
  parsec/api/protocol/events.py
  parsec/backend/events.py
  parsec/core/backend_connection/authenticated.py
  parsec/core/backend_connection/cmds.py
  src/binding_utils.rs
  src/lib.rs
  src/protocol/cmds.rs
  src/protocol/events.rs
  src/protocol/mod.rs
  tests/backend/invite/test_invite_status_changed_event.py
  tests/backend/invite/test_manage_invitations.py
  tests/backend/realm/test_reencryption_maintenance.py
  tests/backend/realm/test_roles_updated_event.py
  tests/backend/realm/test_vlobs_updated_event.py
  tests/backend/test_events.py
  tests/backend/test_message.py
  tests/common/event_bus_spy.py
  tests/core/backend_connection/test_authenticated_cmds.py
  tests/core/backend_connection/test_authenticated_conn.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#3110 Oxidation use gen proto crypto
  newsfragments/3088.empty.rst
  newsfragments/3089.empty.rst
  src/api_crypto.rs
  tests/test_types.py
Labels: python, rust

#3108 Oxidation use gen proto local manifest
  newsfragments/3082.emtpy.rst
  newsfragments/3083.empty.rst
  src/local_manifest.rs
Labels: rust

#3106 Web libparsec bridge generator
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  newsfragments/3137.empty.rst
  oxidation/README.md
  oxidation/bindings/README.md
  oxidation/bindings/android/libparsec/rust/Cargo.toml
  oxidation/bindings/electron/.gitignore
  oxidation/bindings/electron/Cargo.toml
  oxidation/bindings/electron/README.md
  oxidation/bindings/electron/package-lock.json
  oxidation/bindings/electron/package.json
  oxidation/bindings/electron/src/index.d.ts
  oxidation/bindings/electron/src/lib.rs
  oxidation/bindings/electron/src/meths.rs
  oxidation/bindings/generator/api.py
  oxidation/bindings/generator/generate.py
  oxidation/bindings/generator/templates/binding_electron_index.d.ts.j2
  oxidation/bindings/generator/templates/binding_electron_meths.rs.j2
  oxidation/bindings/generator/templates/binding_web_meths.rs.j2
  oxidation/bindings/generator/templates/client_plugin_definitions.d.ts.j2
  oxidation/bindings/generator/test_api.py
  oxidation/bindings/neon/src/index.d.ts
  oxidation/bindings/neon/src/lib.rs
  oxidation/bindings/web/Cargo.toml
  oxidation/bindings/web/src/lib.rs
  oxidation/bindings/web/src/meths.rs
  oxidation/client/.env
  oxidation/client/electron/package.json
  oxidation/client/electron/src/preload.ts
  oxidation/client/electron/src/rt/electron-plugins.ts
  oxidation/client/package.json
  oxidation/client/src/plugins/libparsec/definitions.d.ts
  oxidation/client/src/plugins/libparsec/definitions.ts
  oxidation/client/src/plugins/libparsec/index.ts
  oxidation/client/src/views/TestPage.vue
  oxidation/libparsec/src/lib.rs
Labels: rust, Ionic

#3149 Bugfix protocol invite 2a claimer
  newsfragments/3148.empty.rst
  oxidation/generate_test_data/protocol/invite.py
  oxidation/libparsec/crates/protocol/schema/invited_cmds/invite_2a_claimer_send_hashed_nonce.json
  oxidation/libparsec/crates/protocol/tests/test_invite.rs
  oxidation/libparsec_python/libparsec/types.py
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/cmds.py
  parsec/api/protocol/invite.py
  parsec/backend/invite.py
  parsec/core/backend_connection/cmds.py
  parsec/core/backend_connection/invited.py
  parsec/core/invite/claimer.py
  src/lib.rs
  src/protocol/cmds.rs
  src/protocol/invite.rs
  tests/backend/common.py
  tests/backend/invite/conftest.py
  tests/backend/invite/test_exchange.py
  tests/backend/invite/test_exchange_bad_greeter.py
  tests/backend/invite/test_exchange_good.py
  tests/schemas/builder.py
Labels: bug, python, rust

#3146 Update vlob tests
  oxidation/generate_test_data/protocol/utils.py
  oxidation/generate_test_data/protocol/vlob.py
  oxidation/libparsec/crates/protocol/tests/test_vlob.rs
  parsec/api/protocol/base.py
Labels: rust

#3154 Yolo update organization tests
  oxidation/generate_test_data/protocol/organization.py
  oxidation/libparsec/crates/protocol/tests/test_organization.rs
Labels: python, rust

#3152 Yolo update invite tests
  oxidation/generate_test_data/protocol/invite.py
  oxidation/libparsec/crates/protocol/tests/test_invite.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  src/lib.rs
  src/protocol/invite.rs
Labels: python, rust

#3157 Yolo fix packaging because of rust js bridge
  .github/workflows/package-ci.yml
  oxidation/client/electron/package-lock.json
  oxidation/client/package-lock.json
  oxidation/client/src/plugins/libparsec/index.ts
Labels: bug, ci, Ionic

#3159 Oxidation use gen proto protocol
  newsfragments/3084.empty.rst
  newsfragments/3085.empty.rst
  src/binding_utils.rs
  src/protocol/block.rs
  src/protocol/cmds.rs
  src/protocol/events.rs
  src/protocol/invite.rs
  src/protocol/message.rs
  src/protocol/mod.rs
  src/protocol/organization.rs
  src/protocol/ping.rs
  src/protocol/realm.rs
  src/protocol/vlob.rs
Labels: rust

#3164 Yolo remove old rust tests
  tests/rust/test_invite.py
Labels: python

#3142 Links can now be created with timestamp
  newsfragments/3123.feature.rst
  oxidation/libparsec/crates/types/src/addr.rs
  oxidation/libparsec/crates/types/src/time.rs
  parsec/_parsec_pyi/addrs.pyi
  parsec/_parsec_pyi/time.pyi
  parsec/core/fs/workspacefs/workspacefs.py
  parsec/core/gui/central_widget.py
  parsec/core/gui/file_table.py
  parsec/core/gui/files_widget.py
  parsec/core/gui/mount_widget.py
  parsec/core/gui/tr/parsec_en.po
  parsec/core/gui/tr/parsec_fr.po
  parsec/core/gui/workspaces_widget.py
  src/addrs.rs
  tests/core/gui/test_main_window.py
Labels: enhancement, python, rust
