Repository Scille/parsec-cloud, pull requests merged in 2022-08, with the labels that each got.

#2714 Yolo/update black
  .pre-commit-config.yaml
  parsec/api/data/base.py
  parsec/api/data/invite.py
  parsec/api/data/message.py
  parsec/api/protocol/base.py
  parsec/api/transport.py
  parsec/backend/asgi/__init__.py
  parsec/backend/asgi/administration.py
  parsec/backend/raid5_blockstore.py
  parsec/backend/realm.py
  parsec/core/backend_connection/cmds.py
  parsec/core/backend_connection/proxy.py
  parsec/core/cli/pki.py
  parsec/core/fs/remote_loader.py
  parsec/core/fs/storage/chunk_storage.py
  parsec/core/fs/storage/manifest_storage.py
  parsec/core/fs/storage/workspace_storage.py
  parsec/core/fs/userfs/userfs.py
  parsec/core/fs/workspacefs/file_operations.py
  parsec/core/fs/workspacefs/workspacefile.py
  parsec/core/gui/file_size.py
  parsec/core/gui/workspace_button.py
  parsec/core/invite/claimer.py
  parsec/core/invite/greeter.py
  parsec/core/local_device.py
  parsec/core/logged_core.py
  parsec/core/mountpoint/fuse_operations.py
  parsec/core/mountpoint/winfsp_operations.py
  parsec/core/pki/accepter.py
  parsec/core/pki/plumbing.py
  parsec/core/recovery.py
  parsec/core/types/manifest.py
  parsec/serde/schema.py
  poetry.lock
  pyproject.toml
  tests/api/test_types.py
  tests/backend/realm/test_block.py
  tests/backend/test_postgres_db.py
  tests/common/smartcard.py
  tests/core/fs/test_fs_sync.py
  tests/core/fs/workspacefs/test_file_operations.py
  tests/core/fs/workspacefs/test_file_transactions.py
  tests/core/fs/workspacefs/test_sync_transactions.py
  tests/core/fs/workspacefs/test_workspace_fs.py
  tests/core/fs/workspacefs/test_workspacefile.py
  tests/core/gui/test_file_size_display.py
  tests/core/gui/test_files.py
  tests/fixtures.py
Labels: enhancement

#2770 Oxidation local device schema
  newsfragments/2769.empty.rst
  oxidation/libparsec/crates/client_types/schema/local_device.json
  oxidation/libparsec/crates/client_types/src/local_device.rs
  oxidation/libparsec/crates/serialization_format/src/parser/data.rs
  oxidation/libparsec/crates/serialization_format/src/parser/utils.rs
Labels: rust

#2781 Merge device file
  Cargo.lock
  newsfragments/2782.empty.rst
  oxidation/bindings/common/src/lib.rs
  oxidation/libparsec/crates/client_types/Cargo.toml
  oxidation/libparsec/crates/client_types/src/error.rs
  oxidation/libparsec/crates/client_types/src/lib.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/tests/test_local_device_file.rs
  oxidation/libparsec/crates/core/src/error.rs
  oxidation/libparsec/crates/core/src/lib.rs
  oxidation/libparsec/crates/core/tests/mod.rs
  oxidation/libparsec/crates/core/tests/test_local_device.rs
  oxidation/libparsec/crates/types/src/data_macros.rs
Labels: rust

#2803 Add `timeout` to action `setup-rust`
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/quality-assurance.yml
  .github/workflows/windows-ci.yml
Labels: ci

#2778 Feat/2489 maturin based pyproject 2
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/package-linux.yml
  .github/workflows/package-macos.yml
  .github/workflows/package-windows.yml
  .github/workflows/windows-ci.yml
  Cargo.lock
  Cargo.toml
  build.py
  misc/setup-rust.sh
  newsfragments/2489.empty.rst
  packaging/wheel/wheel_it.py
  parsec/__init__.py
  poetry.lock
  pyproject.toml
  src/lib.rs
  tests/backend/realm/test_shuffle_roles.py
  tests/backend/sequester/test_export.py
  tests/conftest.py
  tests/core/fs/storage/test_workspace_storage.py
  tests/core/fs/test_bootstrap.py
  tests/core/fs/test_fs_idempotent_sync.py
  tests/core/fs/test_fs_offline_restart_and_rwfile.py
  tests/core/fs/test_fs_offline_restart_and_tree.py
  tests/core/fs/test_fs_online_concurrent_tree_and_sync.py
  tests/core/fs/test_fs_online_concurrent_user.py
  tests/core/fs/test_fs_online_rwfile_and_sync.py
  tests/core/fs/test_fs_online_tree_and_sync.py
  tests/core/fs/test_fs_online_user.py
  tests/core/fs/test_sequester.py
  tests/core/fs/test_timestamp_causality.py
  tests/core/fs/workspacefs/test_entry_transactions.py
  tests/core/fs/workspacefs/test_file_transactions.py
  tests/core/fs/workspacefs/test_invalid_data.py
  tests/core/fs/workspacefs/test_workspace_fs.py
  tests/core/fs/workspacefs/test_workspace_reencryption_need.py
  tests/core/fs/workspacefs_timestamped/test_entry_transactions_timestamped.py
  tests/core/fs/workspacefs_timestamped/test_file_transactions_timestamped.py
  tests/core/fs/workspacefs_timestamped/test_sync.py
  tests/core/fs/workspacefs_timestamped/test_workspacefs_timestamped.py
  tests/core/gui/test_files.py
  tests/core/gui/test_validators.py
  tests/core/gui/test_workspace_button.py
  tests/core/gui/test_workspaces.py
  tests/core/mountpoint/test_folder_operations.py
  tests/core/test_sync_monitor_stateful.py
  tests/fuzzing/test_fuzz_core.py
Labels: enhancement, windows, ci, linux, macos, python

#2793 Yolo/merge rust ci testing workflow
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/test-rust-ci.yml
  .github/workflows/windows-ci.yml
Labels: enhancement, ci, rust

#2805 Yolo/improve installation poetry
  .github/actions/setup-python-poetry/action.yml
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/package-linux.yml
  .github/workflows/package-macos.yml
  .github/workflows/package-windows.yml
  .github/workflows/windows-ci.yml
Labels: ci, python

#2807 Remove step `Generate PyQT GUI data`
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/windows-ci.yml
Labels: ci, python

#2815 Oxidation replace invite
  newsfragments/2816.empty.rst
  oxidation/libparsec_python/src/lib.rs
  parsec/_parsec/__init__.pyi
  parsec/_parsec/crypto.pyi
  parsec/_parsec/ids.pyi
  parsec/_parsec/invite.pyi
  parsec/api/data/invite.py
  src/invite.rs
  src/lib.rs
  tests/schemas/api_data.json
Labels: refactor, python, rust

#2823 2822 oxidation replace addrs
  newsfragments/2822.empty.rst
  oxidation/libparsec_python/src/lib.rs
  parsec/_parsec/__init__.pyi
  parsec/_parsec/addrs.pyi
  parsec/api/protocol/invite.py
  parsec/core/gui/commercial.py
  parsec/core/types/__init__.py
  parsec/core/types/backend_address.py
  src/addrs.rs
  src/lib.rs
  tests/rust/test_backend_addr.py
Labels: refactor, python, rust

#1600 [GUI] Use clipboard content as default URL when joining an org
  newsfragments/1598.feature.rst
  parsec/core/gui/custom_dialogs.py
  parsec/core/gui/desktop.py
  parsec/core/gui/main_window.py
  tests/core/gui/test_main_window.py
Labels: stale

#2810 Rework workflow to package `parsec-desktop`
  .github/workflows/package-ci.yml
  .github/workflows/package-macos.yml
  .github/workflows/package-windows.yml
Labels: ci

#2798 Yolo/merge python ci testing workflow
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/test-python-ci.yml
  .github/workflows/windows-ci.yml
Labels: ci, refactor, python

#2829 Yolo/improve workflow ci
  .github/workflows/mock-test-python-ci.yml
  .github/workflows/mock-test-rust-ci.yml
  .github/workflows/test-python-ci.yml
  .github/workflows/test-rust-ci.yml
Labels: ci, python, rust

#2745 Oxidation replace trustchain
  newsfragments/2746.empty.rst
  oxidation/libparsec_python/libparsec/types.py
  oxidation/libparsec_python/src/certif.rs
  oxidation/libparsec_python/src/lib.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/trustchain.pyi
  parsec/api/data/entry.py
  parsec/api/protocol/invite.py
  parsec/api/protocol/sequester.py
  parsec/api/protocol/vlob.py
  parsec/core/remote_devices_manager.py
  parsec/core/trustchain.py
  parsec/core/types/manifest.py
  src/lib.rs
  src/trustchain.rs
  tests/core/test_trustchain.py
  tests/core/test_trustchain_stateful.py
Labels: refactor, python, rust

#2840 Yolo/simplify mock ci
  .github/actions/paths-filter/action.yml
  .github/actions/paths-filter/filters.yml
  .github/workflows/mock-test-python-ci.yml
  .github/workflows/mock-test-rust-ci.yml
  .github/workflows/test-python-ci.yml
  .github/workflows/test-rust-ci.yml
Labels: ci, python, rust, github_actions

#2768 Oxidation replace local device
  Cargo.toml
  newsfragments/2766.empty.rst
  oxidation/libparsec_python/src/lib.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/local_device.pyi
  parsec/_parsec_pyi/time.pyi
  parsec/core/cli/utils.py
  parsec/core/types/__init__.py
  parsec/core/types/local_device.py
  src/lib.rs
  src/local_device.rs
  src/time.rs
  tests/rust/test_local_device.py
  tests/schemas/core_data.json
Labels: refactor, python, rust

#2857 Bump rust version
  .azure-pipelines.yml
  .github/workflows/ci.yml
  .github/workflows/package-ci.yml
  docs/development/quickstart.rst
  misc/setup-rust.sh
  newsfragments/2856.empty.rst
  oxidation/bindings/common/src/lib.rs
  oxidation/libparsec/crates/client_types/src/error.rs
  oxidation/libparsec/crates/client_types/src/local_manifest.rs
  oxidation/libparsec/crates/client_types/tests/test_local_manifest.rs
  oxidation/libparsec/crates/core/src/error.rs
  oxidation/libparsec/crates/core_fs/src/error.rs
  oxidation/libparsec/crates/crypto/src/error.rs
  oxidation/libparsec/crates/protocol/src/handshake.rs
  oxidation/libparsec/crates/types/src/error.rs
  oxidation/libparsec_python/src/ids.rs
  oxidation/libparsec_python/src/invite.rs
  oxidation/libparsec_python/src/lib.rs
  oxidation/libparsec_python/src/manifest.rs
  src/ids.rs
  src/invite.rs
  src/lib.rs
  src/manifest.rs
Labels: rust

#2862 Trigger `test-python-matrix` & `test-rust-matrix` on main branch
  .github/workflows/ci.yml
Labels: bug, ci

#2883 Use official `PostgreSQL` APT repository to install `postgresql-12`
  .github/workflows/ci.yml
  newsfragments/2882.empty.rst
Labels: bug, ci, linux, python

#2888 Remove pendulum
  parsec/core/types/local_device.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#2889 Oxidation bump diesel
  newsfragments/2869.empty.rst
  oxidation/libparsec/crates/core_fs/Cargo.toml
  oxidation/libparsec/crates/core_fs/src/lib.rs
Labels: enhancement, rust

#2838 2825 oxidation replace local manifest
  newsfragments/2825.empty.rst
  oxidation/libparsec_python/src/lib.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/local_manifest.pyi
  parsec/api/data/__init__.py
  parsec/api/data/manifest.py
  parsec/core/fs/remote_loader.py
  parsec/core/fs/storage/manifest_storage.py
  parsec/core/fs/storage/user_storage.py
  parsec/core/fs/storage/workspace_storage.py
  parsec/core/fs/userfs/merging.py
  parsec/core/fs/userfs/userfs.py
  parsec/core/fs/workspacefs/entry_transactions.py
  parsec/core/fs/workspacefs/file_operations.py
  parsec/core/fs/workspacefs/file_transactions.py
  parsec/core/fs/workspacefs/sync_transactions.py
  parsec/core/fs/workspacefs/workspacefs.py
  parsec/core/types/__init__.py
  parsec/core/types/manifest.py
  src/lib.rs
  src/local_manifest.rs
  src/manifest.rs
  tests/api/test_types.py
  tests/core/fs/storage/test_workspace_storage.py
  tests/core/gui/test_files.py
  tests/rust/test_local_manifest.py
  tests/schemas/builder.py
  tests/schemas/core_data.json
Labels: refactor, python, rust

#2771 Add User & Device info
  newsfragments/2772.empty.rst
  oxidation/libparsec/crates/client_types/src/local_device.rs
  oxidation/libparsec/crates/types/src/ext_types.rs
  oxidation/libparsec/crates/types/src/id.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/local_device.pyi
  parsec/core/types/__init__.py
  parsec/core/types/local_device.py
  src/lib.rs
  src/local_device.rs
  tests/core/gui/test_offline.py
  tests/core/gui/test_workspace_button.py
Labels: python, rust

#2892 Oxidation handle unknown status
  Cargo.lock
  newsfragments/2891.empty.rst
  oxidation/bindings/common/Cargo.toml
  oxidation/generate_test_data/protocol/block.py
  oxidation/libparsec/crates/protocol/Cargo.toml
  oxidation/libparsec/crates/protocol/tests/mod.rs
  oxidation/libparsec/crates/protocol/tests/test_common.rs
  oxidation/libparsec/crates/serialization_format/src/parser/protocol.rs
  oxidation/libparsec/crates/types/Cargo.toml
Labels: rust

#2905 Oxidize `file_operations` module python
  newsfragments/2899.empty.rst
  oxidation/libparsec_python/src/lib.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/file_operation.pyi
  parsec/core/fs/storage/manifest_storage.py
  parsec/core/fs/storage/workspace_storage.py
  parsec/core/fs/workspacefs/file_operations.py
  src/file_operations.rs
  src/lib.rs
Labels: refactor, python, rust

#2887 Build web app in CI
  .github/actions/paths-filter/action.yml
  .github/actions/paths-filter/filters.yml
  .github/workflows/ci.yml
  newsfragments/2874.empty.rst
Labels: ci, Ionic

#2855 Replace BlockCreate & BlockRead
  Cargo.lock
  Cargo.toml
  newsfragments/2846.empty.rst
  oxidation/libparsec/crates/protocol/tests/test_vlob.rs
  oxidation/libparsec_python/src/lib.rs
  oxidation/libparsec_python/src/protocol/block.rs
  oxidation/libparsec_python/src/protocol/mod.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/protocol.pyi
  parsec/api/protocol/__init__.py
  parsec/api/protocol/base.py
  parsec/api/protocol/block.py
  parsec/backend/block.py
  parsec/core/backend_connection/cmds.py
  parsec/core/fs/remote_loader.py
  src/lib.rs
  src/protocol/block.rs
  src/protocol/cmds.rs
  src/protocol/mod.rs
  tests/backend/common.py
  tests/backend/realm/test_block.py
  tests/backend/realm/test_reencryption_maintenance.py
  tests/schemas/api_protocol.json
  tests/schemas/builder.py
Labels: refactor, python, rust

#2890 Add job to package electron app
  .github/workflows/package-ci.yml
  newsfragments/2875.empty.rst
  oxidation/bindings/neon/package-lock.json
  oxidation/bindings/neon/package.json
  oxidation/client/electron/electron-builder.config.json
  oxidation/client/electron/package.json
  oxidation/client/electron/src/index.ts
  oxidation/client/electron/src/setup.ts
  oxidation/client/src/router/index.ts
Labels: ci, Ionic

#2950 Yolo/update status badge
  README.rst
Labels: docs

#2958 Format documents files with `editorconfig`
  README.rst
  docs/cryptography.rst
  docs/development/index.rst
  docs/development/release.rst
  docs/hosting_server.rst
  docs/index.rst
  docs/userguide/index.rst
  docs/userguide/share_data.rst
  oxidation/README.md
  oxidation/bindings/README.md
  oxidation/bindings/web/README.md
  tests/scripts/README.md
Labels: docs
