Repository Scille/parsec-cloud, pull requests merged in 2023-05, with the labels that each got.

#4466 Fix shamir RFC
  docs/rfcs/1000-shamir-based-recovery.md
Labels: docs

#4511 Fix `maturin` version to `0.14.15`
  build.py
  pyproject.toml
Labels: bug, dependencies, python

#4532 Disable pdfs generation on read the docs
  .readthedocs.yml
Labels: bug, docs

#4569 Update the pull request template to match the one described in `docs/merging-process.md`
  .github/pull_request_template.md
  docs/development/merging-process.md
Labels: docs

#4586 Replace workflow `release-starter` with updated `releaser.py`
  .github/workflows/release-starter.yml
  docs/development/release.md
  misc/releaser.py
Labels: CI / CD

#4587 Add workflow to publish `testbed` docker image
  .github/workflows/publish-testbed.yml
  packaging/testbed-server/build-testbed.sh
  packaging/testbed-server/build.sh
Labels: CI / CD

#4610 Add documentation for building testbed server
  packaging/server/build.sh
  packaging/testbed-server/README.md
  packaging/testbed-server/build.sh
Labels: CI / CD, docs
