Repository Scille/parsec-cloud, pull requests merged in 2023-11, with the labels that each got.

#5689 Migrate `sequester test guide` wiki page
  docs/development/sequester-test-guide.md
Labels: A-Docs

#5555 Fix share realm with outsider
  libparsec/crates/client/src/certificates_ops/add.rs
  libparsec/crates/client/tests/unit/certificates_ops/add_realm_role_certificate.rs
Labels: bug, I-Rust, testing

#5711 Add `customize_with_map` for `TestbedEnv`
  libparsec/crates/testbed/src/env.rs
Labels: I-Rust, testing

#5713 Add `check_consistency` param to skip testbed check
  libparsec/crates/testbed/src/template/build.rs
  libparsec/crates/testbed/src/template/events.rs
Labels: I-Rust, testing

#5714 Fix `assert_realm_member_has_write_access`
  libparsec/crates/testbed/src/template/utils.rs
Labels: I-Rust, testing

#5538 Add tests for `poll_server_for_new_certificates`
  libparsec/crates/client/src/certificates_ops/poll.rs
  libparsec/crates/client/tests/unit/certificates_ops/mod.rs
  libparsec/crates/client/tests/unit/certificates_ops/poll.rs
Labels: I-Rust, testing

#5695 Use created `vlob_id` by `env`
  libparsec/crates/client/tests/unit/certificates_ops/add_realm_role_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/add_user_update_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/store.rs
  libparsec/crates/testbed/src/env.rs
  libparsec/crates/testbed/src/template/build.rs
Labels: I-Rust, testing

#5721 Simplify `add_device_certificate` tests
  libparsec/crates/client/tests/unit/certificates_ops/add_device_certificate.rs
Labels: I-Rust, testing

#5716 Add tests for `SequesterKey`
  libparsec/crates/crypto/src/common/sequester.rs
  libparsec/crates/crypto/src/sodiumoxide/sequester.rs
  libparsec/crates/crypto/tests/sequester.rs
Labels: I-Rust, testing

#5736 Simplify `add_certificate` tests
  libparsec/crates/client/tests/unit/certificates_ops/add_sequester_authority_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/add_user_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/add_user_revoked_certificate.rs
Labels: I-Rust, testing

#5737 Add `consistency check` disabled feature
  libparsec/crates/testbed/src/template/events.rs
Labels: I-Rust, testing

#5031 Add cargo deny to check licenses
  .cspell/custom-words.txt
  .github/custom-problem-matchers/cargo-deny.json
  .github/workflows/ci-rust.yml
  Cargo.toml
  deny.toml
Labels: I-Rust

#5756 Ignore translation for `history` & `adminguide/hosting`
  docs/Makefile
  docs/locale/fr/LC_MESSAGES/adminguide/hosting/index.po
  docs/locale/fr/LC_MESSAGES/history.po
Labels: A-Docs

#5755 [Backport] Fix `docs` workflow being run without needing to
  .github/workflows/ci.yml
Labels: I-CICD

#5588 Add tests for `CertificatesOps` `validate_manifest`
  libparsec/crates/client/tests/unit/certificates_ops/mod.rs
  libparsec/crates/client/tests/unit/certificates_ops/validate_manifest.rs
  libparsec/crates/testbed/src/env.rs
Labels: I-Rust, testing

#5679 [MS] file list not selectable
  client/src/theme/components/footerList.scss
  client/src/views/workspaces/WorkspacesPage.vue
Labels: A-Client

#5760 Add line numbers display in server docs
  docs/adminguide/hosting/index.rst
Labels: A-Docs

#5742 Use `FsPath` for `mountpoint`
  libparsec/crates/platform_mountpoint/src/lib.rs
  libparsec/crates/platform_mountpoint/src/memfs.rs
  libparsec/crates/platform_mountpoint/src/unix/inode.rs
  libparsec/crates/platform_mountpoint/src/unix/mod.rs
  libparsec/crates/platform_mountpoint/src/windows/mod.rs
  libparsec/crates/platform_mountpoint/src/windows/winify.rs
  libparsec/crates/platform_mountpoint/tests/unit/inode.rs
  libparsec/crates/platform_mountpoint/tests/unit/winfsp.rs
  libparsec/crates/platform_mountpoint/tests/winfsp_tests.rs
  libparsec/crates/types/src/fs_path.rs
Labels: mountpoint, I-Rust

#5655 5630 add documentation for recovery device feature
  docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
  docs/userguide/index.rst
  docs/userguide/recovery_device.rst
  docs/userguide/screens/recovery_device_create_device.png
  docs/userguide/screens/recovery_device_create_device_confirmation.png
  docs/userguide/screens/recovery_device_create_device_re_auth.png
  docs/userguide/screens/recovery_device_menu.png
  docs/userguide/screens/recovery_device_modal.png
  docs/userguide/screens/recovery_device_recover.png
  docs/userguide/screens/recovery_device_recover_confirmation.png
  docs/userguide/screens/recovery_device_recover_new_password.png
  newsfragments/5630.doc.rst
Labels: A-Docs

#5641 Move `@sentry/electron` to `client/electron`
  client/electron/package-lock.json
  client/electron/package.json
  client/electron/src/index.ts
  client/package-lock.json
  client/package.json
  client/src/main.ts
Labels: I-Javascript, A-Client

#5785 Rework `docker-testbed` workflow
  .github/scripts/test-testbed-server.py
  .github/workflows/docker-testbed.yml
  .github/workflows/publish-testbed.yml
  server/packaging/testbed-server/testbed-server.dockerfile
Labels: I-CICD

#5794 Add workflow to build the parsec backend docker image
  .github/workflows/docker-server.yml
  server/packaging/server/build.sh
Labels: I-CICD

#5809 Reword some part of the recovery device documentation
  docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
  docs/userguide/recovery_device.rst
Labels: A-Docs

#5783 [Backport] Add documentation for recovery device
  docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
  docs/userguide/index.rst
  docs/userguide/recovery_device.rst
  docs/userguide/screens/recovery_device_create_device.png
  docs/userguide/screens/recovery_device_create_device_confirmation.png
  docs/userguide/screens/recovery_device_create_device_re_auth.png
  docs/userguide/screens/recovery_device_menu.png
  docs/userguide/screens/recovery_device_modal.png
  docs/userguide/screens/recovery_device_recover.png
  docs/userguide/screens/recovery_device_recover_confirmation.png
  docs/userguide/screens/recovery_device_recover_new_password.png
  newsfragments/5630.doc.rst
Labels: A-Docs

#5815 Bump rust to 1.74
  .pre-commit-config.yaml
  Cargo.toml
  bindings/android/libparsec/rust/Cargo.toml
  bindings/electron/Cargo.toml
  bindings/web/Cargo.toml
  libparsec/Cargo.toml
  libparsec/crates/client/Cargo.toml
  libparsec/crates/client/src/certificates_ops/poll.rs
  libparsec/crates/client_connection/Cargo.toml
  libparsec/crates/crypto/Cargo.toml
  libparsec/crates/crypto/src/rustcrypto/sequester.rs
  libparsec/crates/crypto/src/sodiumoxide/sequester.rs
  libparsec/crates/platform_async/Cargo.toml
  libparsec/crates/platform_device_loader/Cargo.toml
  libparsec/crates/platform_device_loader/src/native/mod.rs
  libparsec/crates/platform_http_proxy/Cargo.toml
  libparsec/crates/platform_mountpoint/Cargo.toml
  libparsec/crates/platform_mountpoint/examples/memfs.rs
  libparsec/crates/platform_storage/Cargo.toml
  libparsec/crates/protocol/Cargo.toml
  libparsec/crates/serialization_format/Cargo.toml
  libparsec/crates/testbed/Cargo.toml
  libparsec/crates/testbed/src/env.rs
  libparsec/crates/tests_fixtures/Cargo.toml
  libparsec/crates/tests_lite/Cargo.toml
  libparsec/crates/tests_macros/Cargo.toml
  libparsec/crates/types/Cargo.toml
  libparsec/crates/types/src/pki.rs
  libparsec/crates/types/tests/manifest.rs
  misc/version_updater.py
  rust-toolchain.toml
  server/Cargo.toml
Labels: I-Rust

#5849 [MS] Adds some randomness in file/folder names in mocks
  client/src/parsec/file.ts
  client/tests/e2e/specs/test_folders_page.ts
Labels: I-Javascript, A-Client
