Repository Scille/parsec-cloud, pull requests merged in 2023-07, with the labels that each got.

#4816 Add async_generator as backend dependency
  poetry.lock
  pyproject.toml
Labels: bug

#4785 Improve testbed template construction
  .cspell/names.txt
  .github/workflows/ci-rust.yml
  .github/workflows/ci-web.yml
  Cargo.lock
  libparsec/crates/client/src/user_ops/mod.rs
  libparsec/crates/client/tests/running_device.rs
  libparsec/crates/client/tests/user_ops_tests/create.rs
  libparsec/crates/client/tests/user_ops_tests/mod.rs
  libparsec/crates/client/tests/user_ops_tests/share.rs
  libparsec/crates/client/tests/user_ops_tests/sync.rs
  libparsec/crates/client_connection/src/testbed.rs
  libparsec/crates/client_connection/tests/cmds.rs
  libparsec/crates/platform_device_loader/src/testbed.rs
  libparsec/crates/platform_device_loader/tests/local_device_file.rs
  libparsec/crates/platform_storage/src/testbed.rs
  libparsec/crates/platform_storage/src/web/mod.rs
  libparsec/crates/platform_storage/src/web/user.rs
  libparsec/crates/platform_storage/tests/certificates.rs
  libparsec/crates/platform_storage/tests/user.rs
  libparsec/crates/testbed/Cargo.toml
  libparsec/crates/testbed/src/env.rs
  libparsec/crates/testbed/src/lib.rs
  libparsec/crates/testbed/src/scope.rs
  libparsec/crates/testbed/src/template/build.rs
  libparsec/crates/testbed/src/template/crc_hash.rs
  libparsec/crates/testbed/src/template/events.rs
  libparsec/crates/testbed/src/template/mod.rs
  libparsec/crates/testbed/src/template/utils.rs
  libparsec/crates/testbed/src/templates/alice_cruising.rs
  libparsec/crates/testbed/src/templates/coolorg.rs
  libparsec/crates/testbed/src/templates/minimal.rs
  libparsec/crates/testbed/src/templates/minimal_client_ready.rs
  libparsec/crates/testbed/src/templates/mod.rs
  libparsec/crates/types/src/manifest.rs
  make.py
  misc/version_updater.py
  server/build.py
  server/packaging/server/build.sh
  server/packaging/server/in-docker-build.sh
  server/packaging/server/server.dockerfile
  server/packaging/server/server.dockerfile.dockerignore
  server/packaging/testbed-server/build.sh
  server/packaging/testbed-server/in-docker-build.sh
  server/packaging/testbed-server/testbed-server.dockerfile.dockerignore
  server/poetry.lock
  server/pyproject.toml
  server/src/lib.rs
  server/src/testbed.rs
Labels: rust

#4872 Simplify add_certificates_batch
  libparsec/crates/client/src/certificates_ops/add.rs
Labels: rust

#4873 Remove useless clone in claimer ctx
  libparsec/crates/client/src/invite/claimer.rs
Labels: rust

#4875 Check that is the right error in `serde_file_manifest_invalid_blocksize`
  libparsec/crates/types/tests/manifest.rs
Labels: rust, testing

#4826 Prevent using `unwrap` in rust codebase outside of tests
  .clippy.toml
  .pre-commit-config.yaml
  libparsec/crates/client/tests/event_bus.rs
  libparsec/crates/client/tests/running_device.rs
  libparsec/crates/client/tests/user_ops_tests/mod.rs
  libparsec/crates/client_connection/tests/cmds.rs
  libparsec/crates/crypto/src/rustcrypto/private.rs
  libparsec/crates/crypto/src/rustcrypto/sign.rs
  libparsec/crates/crypto/tests/hash.rs
  libparsec/crates/crypto/tests/private.rs
  libparsec/crates/crypto/tests/secret.rs
  libparsec/crates/crypto/tests/sequester.rs
  libparsec/crates/crypto/tests/sign.rs
  libparsec/crates/platform_async/tests/eyeballs.rs
  libparsec/crates/platform_device_loader/src/native/local_device_file.rs
  libparsec/crates/platform_device_loader/tests/local_device_file.rs
  libparsec/crates/platform_storage/src/testbed.rs
  libparsec/crates/platform_storage/tests/certificates.rs
  libparsec/crates/platform_storage/tests/user.rs
  libparsec/crates/protocol/tests/block.rs
  libparsec/crates/protocol/tests/events.rs
  libparsec/crates/protocol/tests/invite.rs
  libparsec/crates/protocol/tests/message.rs
  libparsec/crates/protocol/tests/organization.rs
  libparsec/crates/protocol/tests/ping.rs
  libparsec/crates/protocol/tests/pki.rs
  libparsec/crates/protocol/tests/realm.rs
  libparsec/crates/protocol/tests/user.rs
  libparsec/crates/protocol/tests/vlob.rs
  libparsec/crates/serialization_format/tests/data.rs
  libparsec/crates/serialization_format/tests/protocol.rs
  libparsec/crates/testbed/src/lib.rs
  libparsec/crates/tests_fixtures/src/tmp_path.rs
  libparsec/crates/types/src/fixtures.rs
  libparsec/crates/types/src/local_manifest.rs
  libparsec/crates/types/src/protocol.rs
  libparsec/crates/types/tests/addr.rs
  libparsec/crates/types/tests/certif.rs
  libparsec/crates/types/tests/id.rs
  libparsec/crates/types/tests/local_device_file.rs
  libparsec/crates/types/tests/local_manifest.rs
  libparsec/crates/types/tests/manifest.rs
  libparsec/crates/types/tests/message.rs
  libparsec/crates/types/tests/sas_code.rs
  libparsec/crates/types/tests/time.rs
  server/src/addrs.rs
Labels: rust

#4871 Format platform storage correctly
  libparsec/crates/platform_storage/src/native/certificates.rs
  libparsec/crates/platform_storage/src/native/user.rs
  libparsec/crates/platform_storage/src/native/workspace.rs
Labels: rust

#4881 Bump pyo3
  Cargo.lock
  Cargo.toml
  libparsec/crates/serialization_format/src/protocol_python_bindings.rs
  server/src/addrs.rs
  server/src/backend_events.rs
  server/src/binding_utils.rs
  server/src/data/certif.rs
  server/src/data/manifest.rs
  server/src/data/pki.rs
  server/src/time.rs
Labels: rust

#4827 [MS] Added tests for folders page
  client/src/common/mocks.ts
  client/src/components/FileCard.vue
  client/src/views/FoldersPage.vue
  client/tests/component/specs/testFileCard.spec.ts
  client/tests/component/specs/testFileListItem.spec.ts
  client/tests/e2e/specs/test_folders_page.ts
Labels: Ionic

#4911 Clean `client_connection` dependencies
  Cargo.lock
  Cargo.toml
  libparsec/crates/client_connection/Cargo.toml
Labels: dependencies, rust

#4910 Remove useless `diesel` specification
  libparsec/crates/platform_storage/Cargo.toml
Labels: dependencies, rust
