Repository Scille/parsec-cloud, pull requests merged in 2023-02, with the labels that each got.

#3604 Add workflow to trigger code scanning
  .github/workflows/codeql.yml
Labels: enhancement, ci, python, Q&A

#4073 [ci] Retry install npm package
  .github/workflows/ci.yml
Labels: enhancement, ci

#3755 Bump to poetry 1.3.2
  .github/workflows/ci.yml
  .github/workflows/package-ci.yml
Labels: Q&A

#4086 `Regex` are clonable
  oxidation/libparsec/crates/types/src/regex.rs
  src/regex.rs
Labels: rust

#4089 Correct MacOS timeout on the step `build python wheel`
  .github/workflows/package-ci.yml
Labels: ci

#4098 Remove the use uuid in chunk_storage
  oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs
Labels: rust

#4100 Fix typo retrieve
  .github/workflows/ci.yml
  oxidation/bindings/generator/generate.py
  oxidation/libparsec/crates/client_high_level_api/src/fs.rs
  parsec/backend/postgresql/sequester_export.py
  tests/backend/sequester/test_service.py
  tests/core/fs/test_sequester.py
Labels: low
