Repository Scille/parsec-cloud, pull requests merged in 2023-03, with the labels that each got.

#4122 Set werkzeug dependency as optional
  poetry.lock
Labels: python

#4144 Simplify future_id in runtime.rs
  src/runtime.rs
Labels: rust

#4167 Increase timeout when checking out the branch to 2min
  .github/workflows/ci.yml
Labels: ci

#4208 Simplify InvitedCmds binding
  src/backend_connection/invited_cmds.rs
Labels: rust

#4242 Add `__init__.pyi` for storage
  parsec/_parsec_pyi/storage/__init__.pyi
Labels: python

#4243 Simplify UserRemoteLoader
  parsec/core/fs/remote_loader.py
  parsec/core/fs/userfs/userfs.py
Labels: python

#4218 Oxidation log
  .cspell/custom-words.txt
  .github/workflows/ci.yml
  Cargo.lock
  oxidation/libparsec/crates/client_connection/Cargo.toml
  oxidation/libparsec/crates/client_connection/tests/auth_cmds.rs
  oxidation/libparsec/crates/core_fs/Cargo.toml
  oxidation/libparsec/crates/core_fs/src/file_operations.rs
  oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/user_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs
  oxidation/libparsec/crates/platform_async/Cargo.toml
  oxidation/libparsec/crates/platform_async/src/native/sync/notify.rs
  oxidation/libparsec/crates/platform_async/tests/eyeballs.rs
  oxidation/libparsec/crates/platform_device_loader/Cargo.toml
  oxidation/libparsec/crates/platform_device_loader/tests/test_local_device_file.rs
  oxidation/libparsec/crates/platform_local_db/Cargo.toml
  oxidation/libparsec/crates/platform_local_db/src/executor.rs
  oxidation/libparsec/crates/platform_local_db/src/lib.rs
  oxidation/libparsec/crates/platform_local_db/tests/simple.rs
  oxidation/libparsec/crates/testbed/Cargo.toml
  oxidation/libparsec/crates/testbed/src/lib.rs
  oxidation/libparsec/crates/tests_fixtures/Cargo.toml
  oxidation/libparsec/crates/tests_fixtures/src/testbed.rs
Labels: rust

#4261 Fix CI never caching rust artifact
  .github/workflows/ci.yml
Labels: bug, enhancement, ci

#4256 Remove `remote_devices_manager` field from `WorkspaceFS` & `WorkspaceFSTimestamped`
  parsec/core/fs/workspacefs/workspacefs.py
  parsec/core/fs/workspacefs/workspacefs_timestamped.py
Labels: python

#4265 Add timeout to checkout git project to 5min
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/package-ci.yml
Labels: ci

#4270 Use `Ok?` instead of multiple `return`
  oxidation/libparsec/crates/core/src/invite/claimer.rs
  oxidation/libparsec/crates/core/src/invite/greeter.rs
  src/data/local_device_file.rs
Labels: rust

#4255 Add documentation to make a basic benchmark
  docs/development/simple_benchmark.md
Labels: docs

#4275 Remove outdated comment
  oxidation/libparsec/crates/crypto/src/rustcrypto/secret.rs
Labels: rust

#4276 Improve SASCode
  oxidation/libparsec/crates/types/src/invite.rs
Labels: rust

#4266 Update dependabot configuration
  .github/dependabot.yml
Labels: ci, dependencies

#4303 Fix rust test sodiumoxide
  .github/workflows/ci.yml
  oxidation/libparsec/crates/crypto/src/sodiumoxide/secret.rs
Labels: ci, rust

#4305 Use `inputs` instead of `env` for action `setup-python-poetry`
  .github/actions/setup-python-poetry/action.yml
Labels: enhancement, ci

#4311 Simplify storage
  docs/development/simple_benchmark.md
  oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/mod.rs
  oxidation/libparsec/crates/core_fs/src/storage/user_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs
  parsec/_parsec_pyi/storage/workspace_storage.pyi
  src/core_fs/storage/user_storage.rs
  src/core_fs/storage/workspace_storage.rs
  tests/core/gui/test_files.py
Labels: rust

#4342 Bump `diesel_derives` to `2.0.2`
  Cargo.lock
Labels: dependencies, rust
