Repository Scille/parsec-cloud, pull requests merged in 2023-09, with the labels that each got.

#5129 Force personal workspace to mount as letter on windows
  parsec/core/mountpoint/manager.py
  parsec/core/mountpoint/winfsp_runner.py
  tests/core/mountpoint/test_base.py
Labels: windows, mountpoint

#5084 Sse simpler impl
  Cargo.lock
  Cargo.toml
  libparsec/crates/client/src/connection_monitor.rs
  libparsec/crates/client_connection/Cargo.toml
  libparsec/crates/client_connection/src/authenticated_cmds/mod.rs
  libparsec/crates/client_connection/src/authenticated_cmds/sse.rs
  libparsec/crates/client_connection/src/lib.rs
  libparsec/crates/client_connection/tests/cmds.rs
  libparsec/crates/client_connection/tests/unit/rate_limiter.rs
Labels: rust

#5021 Add `winfsp-tests` & `mountpoint` on `windows`
  .cspell/custom-words.txt
  .github/workflows/ci-rust.yml
  Cargo.lock
  Cargo.toml
  libparsec/crates/platform_mountpoint/Cargo.toml
  libparsec/crates/platform_mountpoint/README.md
  libparsec/crates/platform_mountpoint/build.rs
  libparsec/crates/platform_mountpoint/src/error.rs
  libparsec/crates/platform_mountpoint/src/lib.rs
  libparsec/crates/platform_mountpoint/src/memfs.rs
  libparsec/crates/platform_mountpoint/src/windows/error.rs
  libparsec/crates/platform_mountpoint/src/windows/mod.rs
  libparsec/crates/platform_mountpoint/tests/winfsp_tests.rs
Labels: windows, mountpoint, rust, testing

#5182 Expose `parse_backend_addr` for `GUI`
  bindings/electron/src/index.d.ts
  bindings/electron/src/meths.rs
  bindings/generator/api/__init__.py
  bindings/generator/api/addr.py
  bindings/generator/api/common.py
  bindings/generator/api/invite.py
  bindings/generator/api/testbed.py
  bindings/generator/templates/binding_electron_meths.rs.j2
  bindings/web/src/meths.rs
  client/src/plugins/libparsec/definitions.ts
  libparsec/crates/types/src/addr.rs
  libparsec/src/addr.rs
  libparsec/src/lib.rs
Labels: gui, rust

#5198 Get client info for GUI
  bindings/electron/src/index.d.ts
  bindings/electron/src/meths.rs
  bindings/generator/api/client.py
  bindings/web/src/meths.rs
  client/src/plugins/libparsec/definitions.ts
  libparsec/crates/client/src/certificates_ops/mod.rs
  libparsec/crates/client/src/client.rs
  libparsec/crates/client/src/user_ops/error.rs
  libparsec/crates/client/src/user_ops/mod.rs
  libparsec/src/client.rs
Labels: gui, rust

#5260 Migrate `user_get` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/user_get.rs
  libparsec/crates/protocol/tests/user.rs
Labels: rust, testing

#5262 Migrate `organization_stats` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/organization_stats.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/organization_stats.rs
  libparsec/crates/protocol/tests/organization.rs
Labels: rust, testing

#5254 Migrate `vlob_create` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/vlob_create.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/vlob_create.rs
  libparsec/crates/protocol/tests/vlob.rs
Labels: rust, testing

#5266 Migrate `user_create` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/user_create.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/user_create.rs
  libparsec/crates/protocol/tests/user.rs
Labels: rust, testing

#5267 Migrate `organization_config` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/organization_config.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/organization_config.rs
  libparsec/crates/protocol/tests/organization.rs
Labels: rust, testing

#5268 Migrate `user_revoke` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/user_revoke.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/user_revoke.rs
  libparsec/crates/protocol/tests/user.rs
Labels: rust, testing

#5269 Migrate `device_create` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/device_create.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/device_create.rs
  libparsec/crates/protocol/tests/user.rs
Labels: rust, testing

#5273 Migrate `pki_enrollment_submit` tests
  libparsec/crates/protocol/tests/anonymous_cmds/v3/pki_enrollment_submit.rs
  libparsec/crates/protocol/tests/anonymous_cmds/v4/pki_enrollment_submit.rs
  libparsec/crates/protocol/tests/pki.rs
Labels: rust, testing

#5275 Migrate `realm_status` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/realm_status.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/realm_status.rs
  libparsec/crates/protocol/tests/realm.rs
Labels: rust, testing

#5274 Migrate `organization_bootstrap` tests
  libparsec/crates/protocol/tests/anonymous_cmds/v3/organization_bootstrap.rs
  libparsec/crates/protocol/tests/anonymous_cmds/v4/organization_bootstrap.rs
  libparsec/crates/protocol/tests/organization.rs
  libparsec/crates/tests_lite/src/lib.rs
Labels: rust, testing

#5280 Migrate `pki_enrollment_info` tests
  libparsec/crates/protocol/tests/anonymous_cmds/v3/pki_enrollment_info.rs
  libparsec/crates/protocol/tests/anonymous_cmds/v4/pki_enrollment_info.rs
  libparsec/crates/protocol/tests/pki.rs
Labels: rust, testing

#5276 Migrate `realm_stats` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/realm_stats.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/realm_stats.rs
  libparsec/crates/protocol/tests/realm.rs
Labels: rust, testing

#5277 Migrate `realm_get_role_certificates` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/realm_get_role_certificates.rs
  libparsec/crates/protocol/tests/realm.rs
Labels: rust, testing

#5278 Migrate `realm_update_roles` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/realm_update_roles.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/realm_update_roles.rs
  libparsec/crates/protocol/tests/realm.rs
Labels: rust, testing

#5279 Migrate `realm_start_reencryption_maintenance` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/realm_start_reencryption_maintenance.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/realm_start_reencryption_maintenance.rs
  libparsec/crates/protocol/tests/realm.rs
Labels: rust, testing

#5283 Migrate `pki_enrollment_list` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/pki_enrollment_list.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/pki_enrollment_list.rs
  libparsec/crates/protocol/tests/pki.rs
Labels: rust, testing

#5287 Migrate `vlob_update` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/vlob_update.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/vlob_update.rs
  libparsec/crates/protocol/tests/vlob.rs
Labels: rust, testing

#5284 Migrate `realm_finish_reencryption_maintenance` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/realm_finish_reencryption_maintenance.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/realm_finish_reencryption_maintenance.rs
  libparsec/crates/protocol/tests/realm.rs
Labels: rust, testing

#5285 Migrate `pki_enrollment_accept` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/pki_enrollment_accept.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/pki_enrollment_accept.rs
  libparsec/crates/protocol/tests/pki.rs
Labels: rust, testing

#5292 Migrate `vlob_poll_changes` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/vlob_poll_changes.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/vlob_poll_changes.rs
  libparsec/crates/protocol/tests/vlob.rs
Labels: rust, testing

#5286 Migrate `pki_enrollment_reject` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/pki_enrollment_reject.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/pki_enrollment_reject.rs
  libparsec/crates/protocol/tests/pki.rs
Labels: rust, testing

#5294 Migrate `vlob_maintenance_get_reencryption_batch` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/vlob_maintenance_get_reencryption_batch.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/vlob_maintenance_get_reencryption_batch.rs
  libparsec/crates/protocol/tests/vlob.rs
Labels: rust, testing

#5301 Implement `anonymous` `ping` tests
  libparsec/crates/protocol/tests/anonymous_cmds/v3/ping.rs
  libparsec/crates/protocol/tests/anonymous_cmds/v4/ping.rs
Labels: rust, testing

#5293 Migrate `vlob_list_versions` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/vlob_list_versions.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/vlob_list_versions.rs
  libparsec/crates/protocol/tests/vlob.rs
Labels: rust, testing

#5300 Migrate `events_subscribe` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/events_subscribe.rs
  libparsec/crates/protocol/tests/events.rs
Labels: rust, testing

#5295 Migrate `vlob_maintenance_save_reencryption_batch` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/vlob_maintenance_save_reencryption_batch.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/vlob_maintenance_save_reencryption_batch.rs
  libparsec/crates/protocol/tests/vlob.rs
Labels: rust, testing

#5309 Migrate `invite_1_claimer` tests
  libparsec/crates/protocol/tests/invite.rs
  libparsec/crates/protocol/tests/invited_cmds/v3/invite_1_claimer_wait_peer.rs
  libparsec/crates/protocol/tests/invited_cmds/v4/invite_1_claimer_wait_peer.rs
Labels: rust, testing

#5264 Migrate `vlob_read` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v3/vlob_read.rs
  libparsec/crates/protocol/tests/authenticated_cmds/v4/vlob_read.rs
  libparsec/crates/protocol/tests/vlob.rs
Labels: rust, testing

#5315 Migrate `invite_2b_claimer` tests
  libparsec/crates/protocol/tests/invite.rs
  libparsec/crates/protocol/tests/invited_cmds/v3/invite_2b_claimer_send_nonce.rs
  libparsec/crates/protocol/tests/invited_cmds/v4/invite_2b_claimer_send_nonce.rs
Labels: rust, testing

#5312 Migrate `invite_2a_claimer` tests
  libparsec/crates/protocol/tests/invite.rs
  libparsec/crates/protocol/tests/invited_cmds/v3/invite_2a_claimer_send_hashed_nonce.rs
  libparsec/crates/protocol/tests/invited_cmds/v4/invite_2a_claimer_send_hashed_nonce.rs
Labels: rust, testing

#5330 Migrate `invite_info` tests
  libparsec/crates/protocol/tests/invite.rs
  libparsec/crates/protocol/tests/invited_cmds/v3/invite_info.rs
  libparsec/crates/protocol/tests/invited_cmds/v4/invite_info.rs
Labels: rust, testing

#5326 Migrate `invite_4_claimer` tests
  libparsec/crates/protocol/tests/invite.rs
  libparsec/crates/protocol/tests/invited_cmds/v3/invite_4_claimer_communicate.rs
  libparsec/crates/protocol/tests/invited_cmds/v4/invite_4_claimer_communicate.rs
Labels: rust, testing

#5322 Migrate `invite_3b_claimer` tests
  libparsec/crates/protocol/tests/invite.rs
  libparsec/crates/protocol/tests/invited_cmds/v3/invite_3b_claimer_wait_peer_trust.rs
  libparsec/crates/protocol/tests/invited_cmds/v4/invite_3b_claimer_wait_peer_trust.rs
Labels: rust, testing

#5337 Implement `user_update` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v4/user_update.rs
Labels: rust, testing

#5336 Implement `certificate_get` tests
  libparsec/crates/protocol/tests/authenticated_cmds/v4/certificate_get.rs
Labels: rust, testing

#5388 Add help when `version` mismatch
  libparsec/crates/testbed/src/env.rs
Labels: enhancement, rust

#5391 Enhance `ScalarCache` default
  libparsec/crates/client/src/certificates_ops/store.rs
Labels: enhancement, rust

#5390 Remove `get_timestamp_bounds` redirection
  libparsec/crates/client/src/certificates_ops/store.rs
Labels: enhancement, rust

#5389 Remove useless `lifetime`
  libparsec/crates/client/src/certificates_ops/add.rs
  libparsec/crates/testbed/src/template/mod.rs
Labels: enhancement, rust

#5392 Format correctly `check_realm_role_certificate_consistency`
  libparsec/crates/client/src/certificates_ops/add.rs
Labels: enhancement, rust
