Repository Scille/parsec-cloud, pull requests merged in 2023-12, with the labels that each got.

#5924 Link `parsec_cli` in dockerfile
  server/packaging/server/server.dockerfile
  server/packaging/testbed-server/testbed-server.dockerfile
Labels: I-CICD

#5928 Cli: `bootstrap-organization`
  .cspell/custom-words.txt
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/bootstrap_organization.rs
  cli/src/main.rs
  libparsec/src/config.rs
Labels: I-Rust

#5927 Version internal rust crate
  Cargo.lock
  Cargo.toml
  misc/version_updater.py
Labels: I-Rust

#5899 Cli: `run-testenv`
  .cspell/custom-words.txt
  Cargo.lock
  cli/Cargo.toml
  cli/run_testenv.bat
  cli/run_testenv.fish
  cli/run_testenv.sh
  cli/src/bootstrap_organization.rs
  cli/src/create_organization.rs
  cli/src/list_devices.rs
  cli/src/main.rs
  cli/src/run_testenv.rs
  libparsec/crates/platform_device_loader/src/lib.rs
  libparsec/src/config.rs
  libparsec/src/lib.rs
  server/tests/scripts/run_testbed_server.py
Labels: I-Rust

#5973 Add `empty` to `run-testenv`
  cli/src/run_testenv.rs
Labels: I-Rust

#6004 Use less ressource in winfsp-tests
  libparsec/crates/platform_mountpoint/tests/winfsp_tests.rs
Labels: A-Windows, I-Rust

#5942 Cli: `tests`
  .config/nextest.toml
  .github/workflows/ci-rust.yml
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/bootstrap_organization.rs
  cli/src/create_organization.rs
  cli/src/list_devices.rs
  cli/src/main.rs
  cli/src/run_testenv.rs
  cli/src/tests.rs
  libparsec/Cargo.toml
  libparsec/src/lib.rs
Labels: I-CICD, I-Rust

#5770 [MS] Toast style
  client/src/components/users/InvitationListItem.vue
  client/src/locales/en-US.json
  client/src/locales/fr-FR.json
  client/src/main.ts
  client/src/services/notificationManager.ts
  client/src/services/toastManager.ts
  client/src/theme/components/toasts.scss
  client/src/views/devices/DevicesPage.vue
  client/src/views/devices/ExportRecoveryDevicePage.vue
  client/src/views/devices/GreetDeviceModal.vue
  client/src/views/files/FoldersPage.vue
  client/src/views/header/ProfileHeader.vue
  client/src/views/home/CreateOrganizationModal.vue
  client/src/views/home/DeviceJoinOrganizationModal.vue
  client/src/views/home/UserJoinOrganizationModal.vue
  client/src/views/users/ActiveUsersPage.vue
  client/src/views/users/GreetUserModal.vue
  client/src/views/users/InvitationsPage.vue
  client/src/views/users/MyContactDetailsPage.vue
  client/src/views/users/RevokedUsersPage.vue
  client/src/views/workspaces/WorkspaceSharingModal.vue
  client/src/views/workspaces/WorkspacesPage.vue
  client/tests/e2e/specs/test_active_users_page.ts
  client/tests/e2e/specs/test_create_workspace_modal.ts
  client/tests/e2e/specs/test_export_recovery_device_page.ts
  client/tests/e2e/specs/test_folders_page.ts
  client/tests/e2e/specs/test_greet_device_modal.ts
  client/tests/e2e/specs/test_greet_user_modal.ts
  client/tests/e2e/specs/test_invitations_page.ts
  client/tests/e2e/specs/test_my_contact_details_page.ts
  client/tests/e2e/specs/test_workspace_sharing_modal.ts
  client/tests/e2e/specs/test_workspaces_page.ts
  client/tests/e2e/support/index.ts
  client/tests/unit/specs/testNotificationManager.spec.ts
Labels: A-Client
