Repository Scille/parsec-cloud, pull requests merged in 2023-04, with the labels that each got.

#4348 Fix sodiumoxide SequesterCrypto
  Cargo.lock
  oxidation/libparsec/crates/crypto/Cargo.toml
  oxidation/libparsec/crates/crypto/src/sodiumoxide/sequester.rs
  oxidation/libparsec/crates/crypto/tests/sequester.rs
Labels: bug, rust

#4383 Bump parsec macros dependencies
  Cargo.lock
  oxidation/libparsec/crates/serialization_format/Cargo.toml
  oxidation/libparsec/crates/tests_macros/Cargo.toml
  oxidation/libparsec/crates/tests_macros/src/lib.rs
Labels: dependencies, rust

#4399 Bump `thiserror` to `1.0.40` and `jni` to `0.21.1`
  Cargo.lock
  oxidation/bindings/android/libparsec/rust/Cargo.toml
  oxidation/libparsec/crates/client_connection/Cargo.toml
  oxidation/libparsec/crates/client_high_level_api/Cargo.toml
  oxidation/libparsec/crates/core/Cargo.toml
  oxidation/libparsec/crates/core_fs/Cargo.toml
  oxidation/libparsec/crates/crypto/Cargo.toml
  oxidation/libparsec/crates/platform_local_db/Cargo.toml
  oxidation/libparsec/crates/protocol/Cargo.toml
  oxidation/libparsec/crates/types/Cargo.toml
Labels: dependencies, rust

#4402 Don't package `testbed` in `tests_fixtures`
  Cargo.lock
  oxidation/libparsec/crates/client_connection/Cargo.toml
  oxidation/libparsec/crates/client_connection/tests/auth_cmds.rs
  oxidation/libparsec/crates/core_fs/Cargo.toml
  oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/user_storage.rs
  oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs
  oxidation/libparsec/crates/platform_device_loader/tests/test_local_device_file.rs
  oxidation/libparsec/crates/testbed/Cargo.toml
  oxidation/libparsec/crates/testbed/src/lib.rs
  oxidation/libparsec/crates/testbed/src/scope.rs
  oxidation/libparsec/crates/tests_fixtures/Cargo.toml
  oxidation/libparsec/crates/tests_fixtures/src/lib.rs
  oxidation/libparsec/crates/tests_fixtures/src/trustchain.rs
  oxidation/libparsec/crates/tests_macros/src/lib.rs
Labels: enhancement, rust

#4408 Add security policy
  SECURITY.md
Labels: docs

#4376 Split CI workflow into sub-workflows
  .github/filters/ci.yml
  .github/workflows/ci-python.yml
  .github/workflows/ci-rust.yml
  .github/workflows/ci-web.yml
  .github/workflows/ci.yml
Labels: enhancement, CI / CD

#4440 Rework `Q&A` to not require `rust` install.
  .github/workflows/ci-rust.yml
  .github/workflows/ci.yml
Labels: CI / CD, rust

#4445 `npm run web:open` now open a new tab on the web browser
  oxidation/client/package.json
  oxidation/client/vite.config.ts
Labels: Ionic

#4450 Remove `env` variables in `ci.yml`
  .github/workflows/ci.yml
Labels: CI / CD

#4464 Fix typo concent -> consent
  docs/rfcs/1000-shamir-based-recovery.md
Labels: docs
