Repository Scille/parsec-cloud, pull requests merged in 2023-08, with the labels that each got.

#4877 Add test for `impl_manifest_dump_load`
  docs/development/generate_blob.md
  libparsec/crates/types/tests/unit/manifest.rs
Labels: rust, testing

#4957 Fix sbom upload
  .github/workflows/package-server.yml
  .github/workflows/releaser.yml
Labels: bug, CI / CD

#5025 Bump rust version to 1.71.1
  .pre-commit-config.yaml
  bindings/electron/src/meths.rs
  bindings/generator/api/common.py
  bindings/generator/templates/binding_electron_meths.rs.j2
  bindings/web/src/meths.rs
  docs/development/quickstart.md
  libparsec/crates/types/tests/id.rs
  misc/version_updater.py
  rust-toolchain.toml
  server/src/lib.rs
Labels: rust

#5086 Refactor `authenticated_cmds::start_sse`
  Cargo.lock
  libparsec/crates/client_connection/Cargo.toml
  libparsec/crates/client_connection/src/authenticated_cmds.rs
Labels: rust

#5085 Refactor `ConnectionMonitor`
  libparsec/crates/client/src/connection_monitor.rs
Labels: rust
