Repository Scille/parsec-cloud, pull requests merged in 2023-10, with the labels that each got.

#5404 Factorize `CertificatesStore`
  Cargo.lock
  Cargo.toml
  libparsec/crates/client/Cargo.toml
  libparsec/crates/client/src/certificates_ops/add.rs
  libparsec/crates/client/src/certificates_ops/mod.rs
  libparsec/crates/client/src/certificates_ops/poll.rs
  libparsec/crates/client/src/certificates_ops/store.rs
  libparsec/crates/client/src/certificates_ops/validate_manifest.rs
  libparsec/crates/client/src/certificates_ops/validate_message.rs
Labels: enhancement, rust

#5422 Add test prohibit skipping indexes
  libparsec/crates/platform_storage/src/native/certificates.rs
  libparsec/crates/platform_storage/tests/unit/certificates.rs
Labels: bug, rust, testing

#5436 Format correctly `certif` tests
  libparsec/crates/types/tests/certif.rs
Labels: enhancement, rust

#5458 Fix `SequesterAuthority` keys in test
  libparsec/crates/testbed/src/template/build.rs
Labels: bug, rust, testing

#5460 Add `add_certificates_batch` method
  libparsec/crates/client/src/certificates_ops/mod.rs
  libparsec/crates/client/src/certificates_ops/poll.rs
Labels: rust

#5464 Add tests for `CertificatesOps` `add_certificates_batch` common error
  libparsec/crates/client/src/certificates_ops/add.rs
  libparsec/crates/client/src/certificates_ops/mod.rs
  libparsec/crates/client/tests/unit/certificates_ops/add_common.rs
  libparsec/crates/client/tests/unit/certificates_ops/mod.rs
  libparsec/crates/client/tests/unit/certificates_ops/utils.rs
Labels: rust, testing

#5235 Don't use regex for OrganizationID/UserID/DeviceName validation to speedup tests
  Cargo.lock
  Cargo.toml
  libparsec/crates/types/Cargo.toml
  libparsec/crates/types/src/id.rs
  libparsec/crates/types/tests/id.rs
  libparsec/src/validation.rs
Labels: rust

#5467 Add tests for `CertificatesOps` `add_certificates_batch` `user`
  libparsec/crates/client/tests/unit/certificates_ops/add_user_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/mod.rs
  libparsec/crates/testbed/src/env.rs
  libparsec/crates/testbed/src/template/mod.rs
Labels: rust, testing

#5469 Add tests for `CertificatesOps` `add_certificates_batch` `device`
  libparsec/crates/client/tests/unit/certificates_ops/add_device_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/mod.rs
Labels: rust, testing

#5471 Add tests for `CertificatesOps` `add_certificates_batch` `revoked`
  libparsec/crates/client/tests/unit/certificates_ops/add_user_revoked_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/mod.rs
Labels: rust, testing

#5487 Add tests for `CertificatesOps` `add_certificates_batch` `update_user`
  libparsec/crates/client/src/certificates_ops/add.rs
  libparsec/crates/client/tests/unit/certificates_ops/add_user_update_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/mod.rs
  libparsec/crates/testbed/src/template/build.rs
  libparsec/crates/testbed/src/template/events.rs
Labels: rust, testing

#5508 Add link to report a sec vuln
  .github/ISSUE_TEMPLATE/config.yml
Labels: A-Docs

#5506 Add tests for `CertificatesOps` `add_certificates_batch` `sequester_authority`
  libparsec/crates/client/tests/unit/certificates_ops/add_sequester_authority_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/mod.rs
Labels: I-Rust, testing

#5510 Migrate the Glossary from `wiki` to `docs`
  docs/development/glossary.md
Labels: I-Enhancement, A-Docs

#5127 Oxidation fuse
  .cspell/custom-words.txt
  .github/workflows/ci-rust.yml
  Cargo.lock
  Cargo.toml
  libparsec/crates/platform_mountpoint/Cargo.toml
  libparsec/crates/platform_mountpoint/examples/memfs.rs
  libparsec/crates/platform_mountpoint/src/error.rs
  libparsec/crates/platform_mountpoint/src/lib.rs
  libparsec/crates/platform_mountpoint/src/memfs.rs
  libparsec/crates/platform_mountpoint/src/unix/inode.rs
  libparsec/crates/platform_mountpoint/src/unix/mod.rs
  libparsec/crates/platform_mountpoint/src/windows/error.rs
  libparsec/crates/platform_mountpoint/src/windows/mod.rs
  libparsec/crates/platform_mountpoint/tests/base.rs
  libparsec/crates/platform_mountpoint/tests/fuse.rs
  libparsec/crates/platform_mountpoint/tests/unit/inode.rs
  libparsec/crates/platform_mountpoint/tests/winfsp_tests.rs
Labels: mountpoint, I-Rust, testing

#5480 Add tests for `CertificatesOps` `add_certficates_batch` `realm_role`
  libparsec/crates/client/src/certificates_ops/add.rs
  libparsec/crates/client/tests/unit/certificates_ops/add_realm_role_certificate.rs
  libparsec/crates/client/tests/unit/certificates_ops/mod.rs
Labels: I-Rust, testing

#5536 Move optional value after required one
  libparsec/crates/client/src/invite/claimer.rs
  libparsec/crates/client/src/invite/organization.rs
  libparsec/crates/types/src/local_device.rs
Labels: I-Rust

#5550 Add sphinx-copybutton to have a copy button in code blocks in the docs
  .cspell/custom-words.txt
  docs/conf.py
  docs/poetry.lock
  docs/pyproject.toml
Labels: A-Docs

#5130 Add RFC 1003: Mandatory human handle & device label
  .cspell/custom-words.txt
  docs/rfcs/1003-mandatory-human-handle.md
Labels: A-Docs

#5586 Lock `console_error_panic_hook` to version 0.1.6
  Cargo.lock
  Cargo.toml
Labels: I-Rust

#5636 Fix docs docker-image build related to change introduced in #5573
  docs/Dockerfile
  docs/pyproject.toml
Labels: A-Docs

#5645 Remove `development.po`
  docs/locale/fr/LC_MESSAGES/development.po
Labels: A-Docs

#5646 Delete `functional_architecture.po`
  docs/locale/fr/LC_MESSAGES/functional_architecture.po
Labels: A-Docs

#5647 Changelog: linked issue's link is on a new line
  HISTORY.rst
  misc/releaser.py
Labels: A-Docs

#5652 Add workflow to check the doc build status
  .github/filters/ci.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci.yml
  docs/Makefile
  misc/version_updater.py
Labels: I-CICD, A-Docs

#5668 Add function to validate organization id
  bindings/electron/src/index.d.ts
  bindings/electron/src/meths.rs
  bindings/generator/api/validation.py
  bindings/web/src/meths.rs
  client/src/plugins/libparsec/definitions.ts
  libparsec/src/validation.rs
Labels: I-Rust, I-Javascript, A-Client

#5688 Fix typo in `inbound_outbound_sync`
  libparsec/crates/client/src/client.rs
  libparsec/crates/client/src/monitors/base.rs
  libparsec/crates/client/src/monitors/inbound_sync.rs
  libparsec/crates/client/src/running_workspace.rs
  libparsec/crates/platform_async/src/native/mod.rs
  libparsec/crates/platform_async/src/web/mod.rs
Labels: A-Docs

#4398 Oxidize winify
  .cspell/custom-words.txt
  libparsec/crates/client/Cargo.toml
  libparsec/crates/client/src/workspace_ops/merge.rs
  libparsec/crates/platform_mountpoint/src/error.rs
  libparsec/crates/platform_mountpoint/src/windows/mod.rs
  libparsec/crates/platform_mountpoint/src/windows/winify.rs
  libparsec/crates/platform_mountpoint/tests/unit/winify.rs
  libparsec/crates/types/src/fs_path.rs
Labels: I-Enhancement, I-Python, I-Rust
