Repository Scille/parsec-cloud, pull requests merged in 2023-06, with the labels that each got.

#4617 Rename workflow `ci-python` to `CI Python` (previously called `ci-rust` caused by a wrong copy/paste)
  .github/filters/ci.yml
  .github/workflows/ci-python.yml
Labels: CI / CD, python

#4623 Allow to customize the backend host for the testenv
  tests/scripts/run_testenv.py
Labels: python, testing

#4660 Harden permission for workflow `package-ci`
  .github/workflows/package-ci.yml
Labels: CI / CD

#4730 Simplify typing
  parsec/core/fs/remote_loader.py
Labels: python
