Repository Scille/parsec-cloud, pull requests merged in 2023-01, with the labels that each got.

#3800 Oxidation replace organization types
  newsfragments/3798.empty.rst
  newsfragments/3799.empty.rst
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/organization_stats.json5
  oxidation/libparsec/crates/protocol/tests/test_organization.rs
  oxidation/libparsec/crates/serialization_format/src/utils.rs
  oxidation/libparsec/crates/types/src/lib.rs
  oxidation/libparsec/crates/types/src/organization.rs
  oxidation/libparsec/crates/types/src/user.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/organization.pyi
  parsec/_parsec_pyi/protocol/user.pyi
  parsec/_parsec_pyi/user.pyi
  parsec/backend/asgi/administration.py
  parsec/backend/memory/organization.py
  parsec/backend/organization.py
  parsec/backend/postgresql/organization.py
  parsec/core/backend_connection/authenticated.py
  parsec/core/gui/organization_info_widget.py
  parsec/core/logged_core.py
  parsec/core/types/__init__.py
  parsec/core/types/organizations.py
  src/data/mod.rs
  src/data/organization.rs
  src/data/user.rs
  src/protocol/mod.rs
  src/protocol/organization.rs
  tests/core/backend_connection/test_authenticated_conn.py
  tests/core/test_logged_core.py
Labels: python, rust

#3827 Remove oscrypto stubs
  Cargo.lock
  parsec/stubs/oscrypto/__init__.pyi
  parsec/stubs/oscrypto/asymmetric.pyi
  parsec/stubs/oscrypto/errors.pyi
  parsec/stubs/oscrypto/py.typed
Labels: python

#3765 Added virtual entry infos files to winfsp mountpoints
  parsec/core/mountpoint/winfsp_operations.py
  tests/core/mountpoint/test_winfsp.py
Labels: enhancement, windows

#3828 Provide more explicit message on the error reason
  .github/scripts/check_newsfragments.py
Labels: enhancement, ci, Q&A

#3797 Oxidize core event enum
  oxidation/libparsec/crates/core/src/events.rs
  oxidation/libparsec/crates/core/src/lib.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/events.pyi
  parsec/api/protocol/handshake.py
  parsec/api/version.py
  parsec/core/backend_connection/authenticated.py
  parsec/core/core_events.py
  parsec/core/fs/userfs/userfs.py
  parsec/core/fs/workspacefs/entry_transactions.py
  parsec/core/fs/workspacefs/file_transactions.py
  parsec/core/fs/workspacefs/sync_transactions.py
  parsec/core/fs/workspacefs/workspacefs.py
  parsec/core/gui/app.py
  parsec/core/gui/central_widget.py
  parsec/core/gui/enrollment_widget.py
  parsec/core/gui/files_widget.py
  parsec/core/gui/instance_widget.py
  parsec/core/gui/main_window.py
  parsec/core/gui/settings_widget.py
  parsec/core/gui/workspaces_widget.py
  parsec/core/messages_monitor.py
  parsec/core/mountpoint/fuse_operations.py
  parsec/core/mountpoint/fuse_runner.py
  parsec/core/mountpoint/manager.py
  parsec/core/mountpoint/thread_fs_access.py
  parsec/core/mountpoint/winfsp_operations.py
  parsec/core/mountpoint/winfsp_runner.py
  parsec/core/sync_monitor.py
  parsec/event_bus.py
  src/binding_utils.rs
  src/enumerate.rs
  src/lib.rs
  tests/common/core.py
  tests/common/event_bus_spy.py
  tests/common/helpers.py
  tests/core/backend_connection/test_authenticated_conn.py
  tests/core/fs/test_fs_sync.py
  tests/core/fs/test_sequester.py
  tests/core/fs/userfs/test_sharing.py
  tests/core/fs/workspacefs/test_sync_transactions.py
  tests/core/gui/test_notifs.py
  tests/core/gui/test_workspaces.py
  tests/core/mountpoint/test_base.py
  tests/core/mountpoint/test_file_failures.py
  tests/core/mountpoint/test_fuse.py
  tests/core/test_event_entry_updated.py
  tests/core/test_logged_core.py
  tests/core/test_messages_monitor.py
  tests/core/test_sync_monitor.py
Labels: python, rust

#3829 Remove legacy protocol stuff
  parsec/api/protocol/base.py
  parsec/api/protocol/vlob.py
  parsec/core/backend_connection/cmds.py
  parsec/serde/__init__.py
  parsec/serde/schema.py
  tests/backend/common.py
  tests/backend/realm/test_reencryption_maintenance.py
Labels: python

#3835 Improve const enum macro
  parsec/_parsec_pyi/events.pyi
  parsec/_parsec_pyi/protocol/realm.pyi
  parsec/backend/postgresql/realm_queries/get.py
  parsec/backend/postgresql/realm_queries/maintenance.py
  src/binding_utils.rs
  src/enumerate.rs
  src/protocol/realm.rs
Labels: refactor, rust

#3792 Rework organization config active users limit by adding an enum
  oxidation/libparsec/crates/protocol/schema/authenticated_cmds/organization_config.json5
  oxidation/libparsec/crates/protocol/tests/test_organization.rs
  oxidation/libparsec/crates/serialization_format/src/utils.rs
  oxidation/libparsec/crates/types/src/organization.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/organization.pyi
  parsec/_parsec_pyi/protocol/organization.pyi
  parsec/backend/asgi/administration.py
  parsec/backend/cli/run.py
  parsec/backend/config.py
  parsec/backend/memory/organization.py
  parsec/backend/memory/user.py
  parsec/backend/organization.py
  parsec/backend/postgresql/handler.py
  parsec/backend/postgresql/organization.py
  parsec/core/backend_connection/authenticated.py
  parsec/core/gui/organization_info_widget.py
  src/data/organization.rs
  src/protocol/mod.rs
  src/protocol/organization.rs
  tests/backend/organization/test_config.py
  tests/backend/test_administration_rest_api.py
  tests/backend/test_pki.py
  tests/backend/test_postgres_concurrency.py
  tests/backend/test_postgres_db.py
  tests/backend/user/test_user_create.py
  tests/core/backend_connection/test_authenticated_conn.py
  tests/core/gui/users_widget/test_greet.py
  tests/core/gui/users_widget/test_invite.py
  tests/core/test_invite.py
Labels: enhancement, python, rust

#3665 Oxidation replace core pki
  oxidation/libparsec/crates/serialization_format/src/utils.rs
  oxidation/libparsec/crates/types/schema/pki/local_pending_enrollment.json
  oxidation/libparsec/crates/types/schema/pki/x509_certificate.json
  oxidation/libparsec/crates/types/src/error.rs
  oxidation/libparsec/crates/types/src/pki.rs
  oxidation/libparsec/crates/types/tests/test_pki.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/__init__.pyi
  parsec/_parsec_pyi/pki.pyi
  parsec/core/gui/tr/parsec_fr.po
  parsec/core/pki/exceptions.py
  parsec/core/types/pki.py
  parsec/serde/fields.py
  src/addrs.rs
  src/data/error.rs
  src/data/mod.rs
  src/data/pki.rs
  tests/backend/invite/test_manage_invitations.py
  tests/common/smartcard.py
  tests/schemas/core_data.json
Labels: refactor, python, rust

#3849 Chore data
  newsfragments/3850.empty.rst
  newsfragments/3851.empty.rst
  parsec/api/data/__init__.py
  parsec/api/data/base.py
  parsec/api/data/entry.py
  parsec/api/protocol/__init__.py
  parsec/api/protocol/pki.py
  parsec/core/cli/rsync.py
  parsec/core/fs/userfs/merging.py
  parsec/core/types/__init__.py
  parsec/core/types/backend_address.py
  parsec/core/types/base.py
  parsec/test_utils/workspacefs.py
  tests/schemas/builder.py
Labels: enhancement, python

#3881 Oxidize device file type enum
  parsec/_parsec.pyi
  parsec/_parsec_pyi/device.pyi
  src/enumerate.rs
  src/lib.rs
Labels: python, rust

#3884 Add Local device file's missing schemas and tests
  oxidation/generate_test_data/local_file_device.py
  oxidation/libparsec/crates/client_types/src/lib.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/src/test/mod.rs
  oxidation/libparsec/crates/client_types/src/test/test_local_device.rs
Labels: rust

#3891 Bump rust
  .github/workflows/ci.yml
  .github/workflows/package-ci.yml
  docs/development/quickstart.rst
  misc/setup-rust.sh
  oxidation/libparsec/crates/types/src/invite.rs
  rust-toolchain.toml
  src/data/local_manifest.rs
Labels: enhancement, rust

#3887 Oxidize device save
  oxidation/libparsec/crates/client_types/src/local_device.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/tests/test_local_device_file.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/local_device.pyi
  parsec/core/cli/list_devices.py
  parsec/core/cli/utils.py
  parsec/core/gui/authentication_change_widget.py
  parsec/core/gui/claim_device_widget.py
  parsec/core/gui/claim_user_widget.py
  parsec/core/gui/create_org_widget.py
  parsec/core/gui/device_recovery_import_widget.py
  parsec/core/local_device.py
  parsec/test_utils/organization.py
  src/lib.rs
  src/local_device.rs
  tests/core/gui/conftest.py
  tests/core/gui/test_enrollment.py
  tests/core/gui/test_expired_organization.py
  tests/core/gui/test_login.py
  tests/core/gui/test_main_window.py
  tests/core/gui/test_recovery.py
  tests/core/gui/test_workspace_sharing.py
  tests/core/test_local_device.py
  tests/test_cli.py
Labels: python, rust

#3892 Oxidation login
  Cargo.lock
  newsfragments/3843.empty.rst
  oxidation/bindings/electron/src/index.d.ts
  oxidation/bindings/electron/src/meths.rs
  oxidation/bindings/generator/api.py
  oxidation/bindings/generator/generate.py
  oxidation/bindings/generator/templates/binding_electron_index.d.ts.j2
  oxidation/bindings/generator/templates/binding_electron_meths.rs.j2
  oxidation/bindings/generator/templates/binding_web_meths.rs.j2
  oxidation/bindings/generator/templates/client_plugin_definitions.d.ts.j2
  oxidation/bindings/web/src/meths.rs
  oxidation/client/src/plugins/libparsec/definitions.d.ts
  oxidation/client/src/views/TestPage.vue
  oxidation/libparsec/Cargo.toml
  oxidation/libparsec/crates/client_types/Cargo.toml
  oxidation/libparsec/crates/core/Cargo.toml
  oxidation/libparsec/crates/core/src/error.rs
  oxidation/libparsec/crates/core/src/lib.rs
  oxidation/libparsec/crates/core/src/logged_core.rs
  oxidation/libparsec/crates/platform_async/src/lib.rs
  oxidation/libparsec/src/lib.rs
Labels: rust, javascript, Ionic

#3896 Oxidize available device
  Cargo.lock
  oxidation/libparsec/crates/client_types/src/local_device.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/device.pyi
  parsec/_parsec_pyi/local_device.pyi
  parsec/core/cli/list_devices.py
  parsec/core/cli/utils.py
  parsec/core/gui/authentication_change_widget.py
  parsec/core/gui/authentication_choice_widget.py
  parsec/core/gui/claim_device_widget.py
  parsec/core/gui/claim_user_widget.py
  parsec/core/gui/create_org_widget.py
  parsec/core/gui/device_recovery_export_widget.py
  parsec/core/gui/device_recovery_import_widget.py
  parsec/core/gui/instance_widget.py
  parsec/core/gui/login_widget.py
  parsec/core/gui/main_window.py
  parsec/core/local_device.py
  parsec/serde/packing.py
  src/enumerate.rs
  src/lib.rs
  src/local_device.rs
  tests/core/gui/conftest.py
  tests/core/gui/test_login.py
  tests/core/gui/test_main_window.py
  tests/core/test_local_device.py
  tests/test_cli.py
  tests/test_scripts.py
Labels: python, rust

#3914 Oxidize generate new device
  oxidation/libparsec/crates/client_types/src/local_device.rs
  parsec/_parsec_pyi/local_device.pyi
  parsec/core/invite/claimer.py
  parsec/core/invite/organization.py
  parsec/core/local_device.py
  parsec/core/pki/submitter.py
  parsec/test_utils/organization.py
  src/local_device.rs
  tests/common/population.py
Labels: python, rust

#3915 Bump chrono
  Cargo.lock
  oxidation/libparsec/crates/client_connection/Cargo.toml
  oxidation/libparsec/crates/core/Cargo.toml
  oxidation/libparsec/crates/core/tests/test_trustchain.rs
  oxidation/libparsec/crates/tests_fixtures/Cargo.toml
  oxidation/libparsec/crates/tests_fixtures/src/trustchain.rs
  oxidation/libparsec/crates/types/Cargo.toml
  oxidation/libparsec/crates/types/src/time.rs
  src/time.rs
Labels: rust

#3883 Oxidation implement `list_available_devices` for `web` platform
  .cspell/names.txt
  .github/workflows/ci.yml
  .github/workflows/package-ci.yml
  .pre-commit-config.yaml
  Cargo.lock
  newsfragments/3842.empty.rst
  oxidation/bindings/electron/src/index.d.ts
  oxidation/bindings/electron/src/meths.rs
  oxidation/bindings/generator/api.py
  oxidation/bindings/generator/templates/binding_electron_meths.rs.j2
  oxidation/bindings/generator/templates/binding_web_meths.rs.j2
  oxidation/bindings/web/Cargo.toml
  oxidation/bindings/web/src/meths.rs
  oxidation/client/src/plugins/libparsec/definitions.d.ts
  oxidation/client/src/views/TestPage.vue
  oxidation/libparsec/Cargo.toml
  oxidation/libparsec/crates/client_types/src/local_device.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/src/test/test_local_device.rs
  oxidation/libparsec/crates/client_types/tests/test_local_device_file.rs
  oxidation/libparsec/crates/platform_async/Cargo.toml
  oxidation/libparsec/crates/platform_device_loader/Cargo.toml
  oxidation/libparsec/crates/platform_device_loader/src/lib.rs
  oxidation/libparsec/crates/platform_device_loader/src/native/local_device.rs
  oxidation/libparsec/crates/platform_device_loader/src/native/local_device_file.rs
  oxidation/libparsec/crates/platform_device_loader/src/native/mod.rs
  oxidation/libparsec/crates/platform_device_loader/src/web/local_device_file.rs
  oxidation/libparsec/crates/platform_device_loader/src/web/mod.rs
  oxidation/libparsec/crates/platform_device_loader/tests/mod.rs
  oxidation/libparsec/crates/platform_device_loader/tests/test_local_device_file.rs
  oxidation/libparsec/crates/types/src/id.rs
  oxidation/libparsec/src/lib.rs
  src/local_device.rs
Labels: rust, javascript, Ionic

#3917 Oxidize recovery device
  parsec/_parsec.pyi
  parsec/_parsec_pyi/local_device.pyi
  parsec/core/cli/recovery.py
  parsec/core/gui/device_recovery_export_widget.py
  parsec/core/gui/device_recovery_import_widget.py
  parsec/core/local_device.py
  src/lib.rs
  src/local_device.rs
  tests/core/gui/test_recovery.py
  tests/core/test_recovery.py
Labels: python, rust

#3924 Add Request Trait
  Cargo.lock
  oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs
  oxidation/libparsec/crates/protocol/src/lib.rs
  oxidation/libparsec/crates/protocol/tests/test_block.rs
  oxidation/libparsec/crates/protocol/tests/test_events.rs
  oxidation/libparsec/crates/protocol/tests/test_ping.rs
  oxidation/libparsec/crates/serialization_format/Cargo.toml
  oxidation/libparsec/crates/serialization_format/src/protocol.rs
  oxidation/libparsec/crates/serialization_format/tests/test_protocol.rs
  src/protocol/block.rs
  src/protocol/events.rs
  src/protocol/invite.rs
  src/protocol/message.rs
  src/protocol/organization.rs
  src/protocol/ping.rs
  src/protocol/pki.rs
  src/protocol/realm.rs
  src/protocol/user.rs
  src/protocol/vlob.rs
Labels: rust

#3899 Oxidation load device password web
  Cargo.lock
  oxidation/bindings/electron/src/index.d.ts
  oxidation/bindings/electron/src/meths.rs
  oxidation/bindings/generator/api.py
  oxidation/bindings/generator/templates/binding_electron_meths.rs.j2
  oxidation/bindings/web/src/meths.rs
  oxidation/client/src/plugins/libparsec/definitions.d.ts
  oxidation/client/src/views/TestPage.vue
  oxidation/libparsec/crates/client_types/src/error.rs
  oxidation/libparsec/crates/client_types/src/local_device.rs
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/core/Cargo.toml
  oxidation/libparsec/crates/core/src/error.rs
  oxidation/libparsec/crates/core/src/logged_core.rs
  oxidation/libparsec/crates/platform_device_loader/Cargo.toml
  oxidation/libparsec/crates/platform_device_loader/src/lib.rs
  oxidation/libparsec/crates/platform_device_loader/src/native/local_device.rs
  oxidation/libparsec/crates/platform_device_loader/src/native/local_device_file.rs
  oxidation/libparsec/crates/platform_device_loader/src/web/local_device.rs
  oxidation/libparsec/crates/platform_device_loader/src/web/local_device_file.rs
  oxidation/libparsec/crates/platform_device_loader/src/web/mod.rs
  oxidation/libparsec/crates/platform_device_loader/tests/test_local_device_file.rs
  oxidation/libparsec/src/lib.rs
  src/local_device.rs
Labels: rust

#3928 Improve DeviceFile & LegacyDeviceFile
  Cargo.lock
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/src/test/test_local_device.rs
  oxidation/libparsec/crates/client_types/tests/test_local_device_file.rs
  oxidation/libparsec/crates/platform_device_loader/Cargo.toml
  oxidation/libparsec/crates/platform_device_loader/src/native/local_device_file.rs
  oxidation/libparsec/crates/platform_device_loader/tests/test_local_device_file.rs
Labels: enhancement, rust

#3931 Fix CI packaging
  .github/actions/paths-filter/filters.yml
  .github/workflows/ci.yml
  build.py
  oxidation/libparsec/crates/core/Cargo.toml
  oxidation/libparsec/crates/platform_device_loader/src/web/local_device.rs
  oxidation/libparsec/crates/platform_device_loader/src/web/local_device_file.rs
  pyproject.toml
Labels: bug, rust

#3943 Fix available device key file path type
  src/binding_utils.rs
  src/local_device.rs
  tests/core/test_local_device.py
Labels: python, rust

#3948 Oxidation device file
  .cspell/custom-words.txt
  misc/license_headers.py
  oxidation/generate_test_data/local_file_device.py
  oxidation/libparsec/crates/client_types/schema/device_file_password.json
  oxidation/libparsec/crates/client_types/schema/device_file_recovery.json
  oxidation/libparsec/crates/client_types/schema/device_file_smartcard.json
  oxidation/libparsec/crates/client_types/src/local_device_file.rs
  oxidation/libparsec/crates/client_types/tests/test_local_device_file.rs
  oxidation/libparsec/crates/platform_device_loader/src/lib.rs
  oxidation/libparsec/crates/platform_device_loader/src/native/local_device.rs
  oxidation/libparsec/crates/serialization_format/src/utils.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/device_file.pyi
  parsec/api/data/__init__.py
  parsec/core/local_device.py
  src/binding_utils.rs
  src/data/error.rs
  src/data/local_device_file.rs
  src/data/local_manifest.rs
  src/data/manifest.rs
  src/data/message.rs
  src/data/mod.rs
  src/data/organization.rs
  src/data/pki.rs
  src/data/user.rs
  src/enumerate.rs
  src/lib.rs
  src/misc.rs
  src/protocol/error.rs
  src/protocol/events.rs
  src/protocol/pki.rs
  src/runtime.rs
  tests/common/smartcard.py
  tests/fixtures.py
  tests/schemas/__init__.py
  tests/schemas/builder.py
  tests/schemas/core_data.json
  tests/schemas/test_compat.py
Labels: refactor, python, rust

#3612 Add RemoteDevicesManager
  Cargo.lock
  oxidation/libparsec/crates/client_connection/Cargo.toml
  oxidation/libparsec/crates/core/Cargo.toml
  oxidation/libparsec/crates/core/src/error.rs
  oxidation/libparsec/crates/core/src/remote_devices_manager.rs
  oxidation/libparsec/crates/core/src/trustchain.rs
  oxidation/libparsec/crates/core/tests/test_trustchain.rs
  src/trustchain.rs
Labels: rust

#3922 Authenticated cmds binding
  Cargo.lock
  oxidation/libparsec/Cargo.toml
  oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs
  oxidation/libparsec/crates/client_connection/src/client.rs
  oxidation/libparsec/crates/client_connection/src/lib.rs
  oxidation/libparsec/crates/client_connection/tests/auth_cmds.rs
  oxidation/libparsec/crates/client_connection/tests/utils/server.rs
  oxidation/libparsec/src/lib.rs
  parsec/_parsec.pyi
  parsec/_parsec_pyi/backend_connection.pyi
  src/backend_connection/authenticated_cmds.rs
  src/backend_connection/error.rs
  src/backend_connection/mod.rs
  src/binding_utils.rs
  src/data/message.rs
  src/lib.rs
  src/protocol/mod.rs
  tests/core/backend_connection/test_authenticated_cmds.py
  tests/test_cli.py
Labels: python, rust

#3764 Windows icon handlers
  .cspell/cspell.config.yml
  .github/workflows/package-ci.yml
  misc/license_headers.py
  packaging/windows/README.md
  packaging/windows/freeze_program.py
  packaging/windows/installer.nsi
  parsec/_parsec_pyi/backend_connection.pyi
  parsec/_parsec_pyi/misc.pyi
  parsec/_parsec_pyi/organization.pyi
  parsec/_parsec_pyi/protocol/error.pyi
  parsec/_parsec_pyi/user.pyi
  windows-icon-handler/.gitignore
  windows-icon-handler/check-icon-handler/CheckIconHandler.cpp
  windows-icon-handler/check-icon-handler/CheckIconHandler.h
  windows-icon-handler/check-icon-handler/CheckIconHandler.rgs
  windows-icon-handler/check-icon-handler/check-icon-handler.cpp
  windows-icon-handler/check-icon-handler/check-icon-handler.def
  windows-icon-handler/check-icon-handler/check-icon-handler.rc
  windows-icon-handler/check-icon-handler/check-icon-handler.rgs
  windows-icon-handler/check-icon-handler/check-icon-handler.vcxproj
  windows-icon-handler/check-icon-handler/check-icon-handler.vcxproj.filters
  windows-icon-handler/check-icon-handler/check-icon-handlerps.def
  windows-icon-handler/check-icon-handler/check.ico
  windows-icon-handler/check-icon-handler/checkiconhandler.idl
  windows-icon-handler/check-icon-handler/dllmain.cpp
  windows-icon-handler/check-icon-handler/dllmain.h
  windows-icon-handler/check-icon-handler/framework.h
  windows-icon-handler/check-icon-handler/icon1.ico
  windows-icon-handler/check-icon-handler/pch.cpp
  windows-icon-handler/check-icon-handler/pch.h
  windows-icon-handler/check-icon-handler/resource.h
  windows-icon-handler/check-icon-handler/targetver.h
  windows-icon-handler/common/include/parsec.h
  windows-icon-handler/external/include/json/json.hpp
  windows-icon-handler/refresh-icon-handler/RefreshIconHandler.cpp
  windows-icon-handler/refresh-icon-handler/RefreshIconHandler.h
  windows-icon-handler/refresh-icon-handler/RefreshIconHandler.rgs
  windows-icon-handler/refresh-icon-handler/dllmain.cpp
  windows-icon-handler/refresh-icon-handler/dllmain.h
  windows-icon-handler/refresh-icon-handler/framework.h
  windows-icon-handler/refresh-icon-handler/pch.cpp
  windows-icon-handler/refresh-icon-handler/pch.h
  windows-icon-handler/refresh-icon-handler/refresh-icon-handler.cpp
  windows-icon-handler/refresh-icon-handler/refresh-icon-handler.def
  windows-icon-handler/refresh-icon-handler/refresh-icon-handler.rc
  windows-icon-handler/refresh-icon-handler/refresh-icon-handler.rgs
  windows-icon-handler/refresh-icon-handler/refresh-icon-handler.vcxproj
  windows-icon-handler/refresh-icon-handler/refresh-icon-handler.vcxproj.filters
  windows-icon-handler/refresh-icon-handler/refresh-icon-handlerps.def
  windows-icon-handler/refresh-icon-handler/refresh.ico
  windows-icon-handler/refresh-icon-handler/refreshiconhandler.idl
  windows-icon-handler/refresh-icon-handler/resource.h
  windows-icon-handler/refresh-icon-handler/targetver.h
  windows-icon-handler/refresh-icon-handlerPS/refresh-icon-handlerPS.vcxproj
  windows-icon-handler/refresh-icon-handlerPS/refresh-icon-handlerPS.vcxproj.filters
  windows-icon-handler/windows-icon-handler.sln
Labels: enhancement, windows, ci

#3968 Migrate test_types
  oxidation/libparsec/crates/crypto/tests/anti_leak.rs
  oxidation/libparsec/crates/types/src/addr.rs
  oxidation/libparsec/crates/types/src/id.rs
  oxidation/libparsec/crates/types/tests/mod.rs
  oxidation/libparsec/crates/types/tests/test_addr.rs
  oxidation/libparsec/crates/types/tests/test_id.rs
  oxidation/libparsec/crates/types/tests/test_time.rs
  src/addrs.rs
  tests/test_types.py
Labels: enhancement, python, rust
