Repository Scille/parsec-cloud, pull requests merged in 2024-01, with the labels that each got.

#6065 Cli: cancel-invitation
  cli/src/cancel_invitation.rs
  cli/src/main.rs
  cli/src/tests.rs
Labels: I-Rust

#6019 [MS] Update grid style
  client/package-lock.json
  client/package.json
  client/src/components/files/FileCard.vue
  client/src/components/users/UserCard.vue
  client/src/theme/components/tags.scss
  client/src/theme/global.scss
  client/src/theme/variables/fonts.scss
  client/src/views/files/FoldersPage.vue
  client/src/views/users/ActiveUsersPage.vue
  client/tests/component/specs/testFileCard.spec.ts
  client/tests/e2e/specs/test_active_users_page.ts
  client/tests/e2e/specs/test_folders_page.ts
  client/tests/e2e/support/index.ts
  client/tsconfig.json
Labels: C-GUI, A-Client

#6016 [MS] Add validity state to inputs
  client/src/common/validators.ts
  client/src/components/core/ms-input/MsInput.vue
  client/src/components/core/ms-modal/MsTextInputModal.vue
  client/src/components/organizations/ChooseServer.vue
  client/src/components/users/UserInformation.vue
  client/src/locales/en-US.json
  client/src/locales/fr-FR.json
  client/src/main.ts
  client/src/services/translation.ts
  client/src/views/devices/ImportRecoveryDevicePage.vue
  client/src/views/home/CreateOrganizationModal.vue
  client/src/views/home/DeviceJoinOrganizationModal.vue
  client/src/views/home/HomePage.vue
  client/tests/e2e/specs/test_create_org_modal.ts
  client/tests/e2e/specs/test_home_page.ts
  client/tests/unit/specs/testValidators.spec.ts
Labels: C-GUI, A-Client

#6079 Cli stats organization
  cli/src/main.rs
  cli/src/run_testenv.rs
  cli/src/stats_organization.rs
  cli/src/tests.rs
Labels: I-Rust

#6075 Cli: remove-device
  cli/src/main.rs
  cli/src/remove_device.rs
  cli/src/tests.rs
  cli/src/utils.rs
Labels: I-Rust

#6071 Cli: export-recovery-device
  cli/src/export_recovery_device.rs
  cli/src/main.rs
  cli/src/tests.rs
  cli/src/utils.rs
Labels: I-Rust

#6081 Cli stats server
  cli/src/main.rs
  cli/src/stats_server.rs
  cli/src/tests.rs
Labels: I-Rust

#6068 Cli: list-invitations
  cli/src/cancel_invitation.rs
  cli/src/list_invitations.rs
  cli/src/main.rs
  cli/src/tests.rs
Labels: I-Rust

#6037 [MS] Update greet device modal
  client/package-lock.json
  client/package.json
  client/src/locales/en-US.json
  client/src/locales/fr-FR.json
  client/src/parsec/greet_device.ts
  client/src/views/devices/GreetDeviceModal.vue
  client/tests/e2e/specs/test_greet_device_modal.ts
Labels: C-GUI, A-Client

#6073 Cli: import-recovery-device
  cli/src/import_recovery_device.rs
  cli/src/main.rs
  cli/src/tests.rs
Labels: I-Rust

#6084 CLI: status-organization
  cli/src/main.rs
  cli/src/status_organization.rs
  cli/src/tests.rs
Labels: I-Rust

#6100 CLI: enhance InvitationToken parsing
  cli/src/cancel_invitation.rs
  cli/src/greet_invitation.rs
Labels: I-Enhancement, I-Rust

#6097 Cli list workspaces
  cli/src/list_workspaces.rs
  cli/src/main.rs
  cli/src/tests.rs
Labels: I-Rust

#6101 Cli list users
  cli/src/list_users.rs
  cli/src/main.rs
  cli/src/tests.rs
  libparsec/crates/client/src/user_ops/mod.rs
Labels: I-Rust

#6099 Cli share workspace
  cli/src/create_workspace.rs
  cli/src/list_users.rs
  cli/src/main.rs
  cli/src/share_workspace.rs
  cli/src/tests.rs
  cli/src/utils.rs
  libparsec/crates/types/src/manifest.rs
Labels: I-Rust

#6117 [Backport] Document `offline mode` feature for workspace
  docs/locale/fr/LC_MESSAGES/userguide/workspace_offline_mode.po
  docs/userguide/index.rst
  docs/userguide/screens/workspace_context_menu.png
  docs/userguide/screens/workspace_offline_modal_disabled.png
  docs/userguide/screens/workspace_offline_modal_enabled.png
  docs/userguide/workspace_offline_mode.rst
Labels: A-Docs, A-Client

#6120 CLI: enhance list-workspaces by adding self role
  cli/src/list_workspaces.rs
  cli/src/tests.rs
  libparsec/crates/types/src/manifest.rs
Labels: I-Rust

#6125 Remove the useless `pub` in `ParsecUrlAsHTTPScheme`
  libparsec/crates/types/src/addr.rs
Labels: I-Rust

#6126 Shorten `From` trait for `CertificateSignerRef` using `Self`
  libparsec/crates/types/src/certif.rs
Labels: I-Rust

#6127 Fix typo in `UserProfile`'s `from_str` method: Error message
  libparsec/crates/types/src/id.rs
Labels: I-Rust

#6128 Add comment for `UserOps`' `sync` method
  libparsec/crates/client/src/user_ops/mod.rs
Labels: I-Rust

#6132 Remove useless transform for VlobID
  libparsec/crates/client/src/user_ops/sync.rs
Labels: I-Rust

#6134 Shorten DeviceName to DeviceLabel
  libparsec/crates/types/src/id.rs
Labels: I-Rust
