Repository Scille/parsec-cloud, pull requests merged in 2024-03, with the labels that each got.

#6280 Add tests for CertifOps: encrypt_for_realm
  libparsec/crates/client/tests/unit/certif/encrypt_for_realm.rs
  libparsec/crates/client/tests/unit/certif/mod.rs
Labels: I-Rust, testing

#6601 Remove `with_testbed_template` argument
  cli/src/run_testenv.rs
  cli/src/utils.rs
  libparsec/crates/platform_device_loader/src/lib.rs
  libparsec/crates/platform_device_loader/src/testbed.rs
  libparsec/crates/platform_device_loader/tests/change_auth.rs
  libparsec/crates/platform_device_loader/tests/load.rs
  libparsec/crates/platform_device_loader/tests/save.rs
  libparsec/src/client.rs
Labels: I-Rust

#6275 Add tests for CertifOps: share_realm
  libparsec/crates/client/tests/unit/certif/mod.rs
  libparsec/crates/client/tests/unit/certif/share_realm.rs
Labels: I-Rust, testing

#6564 Add `keyring`
  .cspell/custom-ext.txt
  .github/workflows/ci-rust.yml
  Cargo.lock
  Cargo.toml
  bindings/electron/src/index.d.ts
  bindings/electron/src/meths.rs
  bindings/generator/api/client.py
  bindings/generator/api/invite.py
  bindings/web/src/meths.rs
  cli/src/utils.rs
  client/src/plugins/libparsec/definitions.ts
  libparsec/crates/client/src/invite/claimer.rs
  libparsec/crates/client/src/invite/organization.rs
  libparsec/crates/platform_device_loader/Cargo.toml
  libparsec/crates/platform_device_loader/src/lib.rs
  libparsec/crates/platform_device_loader/src/native/mod.rs
  libparsec/crates/platform_device_loader/src/testbed.rs
  libparsec/crates/platform_device_loader/tests/change_auth.rs
  libparsec/crates/platform_device_loader/tests/save_load.rs
  libparsec/crates/types/schema/local_device/device_file_keyring.json5
  libparsec/crates/types/src/local_device.rs
  libparsec/crates/types/src/local_device_file.rs
  libparsec/crates/types/tests/local_device_file.rs
  libparsec/src/client.rs
  libparsec/src/invite.rs
  server/src/enumerate.rs
  server/src/lib.rs
Labels: I-Rust, I-Javascript, testing

#6625 Improve keyring strategy
  Cargo.lock
  libparsec/crates/platform_device_loader/Cargo.toml
  libparsec/crates/platform_device_loader/src/native/mod.rs
  libparsec/crates/types/schema/local_device/device_file_keyring.json5
  libparsec/crates/types/src/local_device.rs
  libparsec/crates/types/src/local_device_file.rs
  libparsec/crates/types/tests/local_device_file.rs
Labels: I-Rust

#6863 fix links displaying error if app already opened
  client/electron/src/setup.ts
Labels: bug, A-Client

#6918 [MS] fixes links opening multiple times of second instances
  client/electron/src/index.ts
  client/electron/src/setup.ts
Labels: bug, A-Client
